ironrdp/fuzz/Cargo.toml, ironrdp/fuzz/fuzz_targets/fuzz_capability_sets.rs, ironrdp/src/rdp/capability_sets.rs
This PR fixes a panic where we would attempt to initialize a vector with a negative size when the provided length was too small.
It also adds a fuzzer for capability sets.
=> Fuzz capability sets

ironrdp/Cargo.toml, ironrdp/src/rdp/vc/dvc/gfx/zgfx.rs, ironrdp/src/rdp/vc/dvc/gfx/zgfx/tests.rs
- Update bitvec to the latest version (0.17.1);
- Fixed broken tests;
- Optimized according to the new version's opportunities.
=> Updated bitvec crate the latest version

ironrdp/src/rdp/server_license/server_license_request/cert.rs
Actually the certificate length can be more than 1024 bytes - 1277 for example. So I increated the maximum certificate length.
=> Increase the maximum certificate length

ironrdp_client/Cargo.toml, ironrdp_client/src/active_session.rs, ironrdp_client/src/active_session/codecs/rfx.rs, ironrdp_client/src/active_session/fast_path.rs, ironrdp_client/src/active_session/x224.rs, ironrdp_client/src/config.rs, ironrdp_client/src/connection_sequence.rs, ironrdp_client/src/connection_sequence/user_info.rs, ironrdp_client/src/errors.rs, ironrdp_client/src/lib.rs, ironrdp_client/src/main.rs, ironrdp_client/src/transport.rs, ironrdp_client/src/transport/channels.rs, ironrdp_client/src/transport/connection.rs, ironrdp_client/src/utils.rs
1. Moved out all independent parts to the lib.rs file;
2. Updated connection sequence and active stage parts to be independent of the underlying streams (via traits);
3. Moved connection sequence to the separate function to make the ability to reuse the function.
=> Update IronRDP client to be able to be reused in web-based client

ironrdp/Cargo.toml, ironrdp/src/preconnection.rs
This PR introduces a few improvements to the Preconnection PDU parsing, which were made in the scope of Devolutions Jet JWT routing feature implementation.
Changes:
- Changed InvalidDataLength errors to io::Error(ErrorKind::Eof,...) where more data is required to parse the packet. Thiss will make Preconnection PDU parsing error handling consistent with other PDU parsers. Without this change, it is hard to tell if PDU parsing is actually failed or buffer just had not enough data
- Moved around preconnection PDU header check code to eliminate case, when we could read first 4 bytes of the packet and immediately use it as required PDU data buffer size to allocate, which can cause some nasty out-of-memory errors
=> Preconnection PDU parsing improvements

ironrdp/src/gcc/core_data.rs, ironrdp/src/gcc/core_data/client.rs, ironrdp/src/gcc/core_data/server.rs
Newer RDP clients or server with the Windows 10 2004 update advertised RDP protocol 10.8, which caused issues with conversion to the RdpVersion enum that lacked this new value. I added a few of the expected future protocol version values, and also added a "VUnknown" element as a safety net for any unknown protocol versions. If we see a value we don't know, we can just ignore it, it is just an indicator, not something that should cause a hard protocol failure.
=> Fix Windows 10 2004 update connectivity (RDP client or server)

ironrdp/src/basic_output/bitmap.rs
Trivial:  Fix a couple of spelling errors in error messages
=> Fix spelling errors in Bitmap error codes

ironrdp_client/Cargo.toml, ironrdp_client/src/connection_sequence.rs, ironrdp_client/src/errors.rs, ironrdp_client/src/main.rs
* Changed the `CredSspClient` creation according to changes in the `sspi-rs`
* ~~Replace `rustls` with `native-tls`: when using TLS 1.2 `rustls` sets *record version = 1.0* and *client version = 1.2*  in client hello request and Windows RDP server rejects such messages. `native-tls` sets 1.2 in both places. Also, I've added a comment about it in the code (see `Cargo.toml`).~~
* Add optional support for `native-tls`
=> Integrate new sspi-rs Kerberos module in ironrdp client and add support for `native-tls` as TLS backend

ironrdp/src/lib.rs, ironrdp/src/mcs.rs, ironrdp/src/x224.rs, ironrdp_client/Cargo.toml, ironrdp_client/src/active_session.rs, ironrdp_client/src/active_session/fast_path.rs, ironrdp_client/src/active_session/x224.rs, ironrdp_client/src/codecs.rs, ironrdp_client/src/connection_sequence.rs, ironrdp_client/src/errors.rs, ironrdp_client/src/lib.rs, ironrdp_client/src/main.rs, ironrdp_client/src/transport.rs, ironrdp_client/src/transport/connection.rs
This is part 2 of a 3 part PR with the intent to add a minimal GUI on top of IronRDP. 
Soliciting feedback if this is the right approach for moving ahead. The problem with IronRDP in the current state is that the connection stream is synchronous. This makes it hard to send events from client side while waiting for a message from the RDP server. In the prototype i created for the interactive client i had a hack [here](https://github.com/msabansal/IronRDP/blob/gui/ironrdp_client/src/utils/cloneable_stream.rs) which would allow for the data to be send while waiting for messages. The proper way to do this in my opinion is to make the client asynchronous. 
This PR contains the minimal set of changes to enable that. The basic premise being we asynchronously wait for a full X224 frame to arrive …
=> Adding helper method for async

ironrdp-cli/Cargo.toml, ironrdp-cli/src/main.rs, ironrdp-devolutions-gateway/src/lib.rs, ironrdp-gui-client/Cargo.toml, ironrdp-gui-client/src/main.rs, ironrdp-session/Cargo.toml, ironrdp-session/src/errors.rs, ironrdp/Cargo.toml
Building with `native-tls` is essential cause rustls doesn't allow to connect to Windows 7,8.1 without adding enhanced SSL cipher suites  
=> fix(ironrdp-session, ironrdp. ironrp-cli, ironrdp-gui-client): fix bulding with native-tls

ironrdp-core/src/basic_output/fast_path.rs, ironrdp-core/src/basic_output/fast_path/test.rs
Sometimes the FastPathUpdatePdu header has the
COMPRESSION_USED bit flipped and it returns an error. It should not.
=> fix: do not returns an error when compression is used

.github/workflows/ci.yml, .github/workflows/fuzz.yml, xtask/src/cli.rs, xtask/src/main.rs, xtask/src/tasks.rs
Fetching the corpus in the main CI worflow is a problem because it will fail when the azure storage is modified during the download:
> ERROR: The specified blob does not exist.
> RequestId:76c40723-901e-0098-38b9-8215c9000000
> Time:2023-05-09T21:03:10.8992962Z
> ErrorCode:BlobNotFound
This occurs when there are multiple runs at the same time. This happens for example when two pull requests are opened. This will cause CI to go red for no good reason.
With this patch, main CI will simply run the fuzz targets without using the corpus, as a sanity check. Then, another workflow will run at 03:12 AM UTC on Sunday, Monday, and Saturday using the corpus from azure storage.
Future work: make the scheduled run fuzz longer and in parallel.
cc @pacmancoder
=> ci: separate workflow for fuzzing using corpus

crates/ironrdp-connector/src/connection.rs
This flag is used to indicate that the client supports asymmetric keys larger than 512 bits for use with the Server Certificate (section 2.2.1.4.3.1) sent in the Server Security Data block (section 2.2.1.4.3).
This is supported by IronRDP.
=> feat(connector): support for strong asymmetric keys

crates/ironrdp-tls/Cargo.toml
because it's unusable without one of rustls or native-tls selected.
=> Gives ironrdp-tls a default feature set

fuzz/Cargo.lock
Breakage was caused by some bad interaction with a transitive dependency (proc-macro2).
This is simply updating the Cargo.lock by running `cargo update`.
=> build(fuzz): fix build

crates/ironrdp-pdu/src/basic_output/bitmap.rs
Hi, I found some issues with buffer_length for some pdus related to bitmap display updates.
[TS_UPDATE_BITMAP_DATA](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/d681bb11-f3b5-4add-b092-19fe7075f9e3): 4 bytes header + length of rectangles
[TS_BITMAP_DATA](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/84a3d4d2-5523-4e49-9a48-33952c559485): 18 bytes header + 8 bytes optional header + length of data
=> fix(pdu): buffer_length for bitmap updates

crates/ironrdp-connector/src/channel_connection.rs
According to [this](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/c2bb6f47-779c-42d4-98f3-d7afa2a4906b), during the channel connection phase, the client is supposed to also join the user channel id.
FreeRDP already does this.
This isn't the cleanest fix, but it's simple.
=> fix(connector): client should also join user channel id

crates/ironrdp-pdu/src/lib.rs
Hi, I've been running into an error with `read_pdu` when it's trying to decode the tpkt header of a x224 packet but the internal buffer doesn't yet contain the 4 bytes of the header.
Adding this `ensure_enough` fixes it, and a similar check is made for fast path packets too.
=> fix(pdu): ensure_enough before trying to parse tpkt header

Cargo.lock, Cargo.toml, crates/ironrdp-client/Cargo.toml, crates/ironrdp-web/Cargo.toml, crates/ironrdp-web/src/network_client.rs, crates/ironrdp-web/src/session.rs
- Actually implement sspi-rs’s `NetworkClient` trait in `ironrdp-web`
- Enable the `dns_resolver` feature for `ironrdp-client` (the native client)
Closes #155
=> feat: enable additional sspi features (KDC)

Cargo.lock, crates/ironrdp-web/Cargo.toml, crates/ironrdp-web/src/session.rs, web-client/iron-remote-gui/package-lock.json
Ideally, when the WebSocket can’t be opened, the call to `WebSocket::open` should fail with details on why is that (e.g., the proxy hostname could not be resolved, proxy service is not running), but errors are neved bubbled up in practice, so instead we poll the WebSocket state until we know its connected (i.e., the WebSocket handshake is a success and user data can be exchanged).
For instance, here is the new error shown to the user when the proxy service is not running:
Compare with:
The RDCleanPath packet is not supposed to be relevant when the service is not even running.
=> fix(web): detect errors when opening WebSocket

Cargo.lock, Cargo.toml
To include this patch: https://github.com/Devolutions/sspi-rs/pull/142
=> chore(deps): bump sspi to 0.10.1

Cargo.lock, Cargo.toml, crates/ironrdp-client/Cargo.toml, crates/ironrdp-client/src/rdp.rs, crates/ironrdp-cliprdr/Cargo.toml, crates/ironrdp-cliprdr/src/lib.rs, crates/ironrdp-cliprdr/src/pdu/capabilities.rs, crates/ironrdp-cliprdr/src/pdu/format_data/file_list.rs, crates/ironrdp-cliprdr/src/pdu/format_data/metafile.rs, crates/ironrdp-cliprdr/src/pdu/format_list.rs, crates/ironrdp-cliprdr/src/pdu/mod.rs, crates/ironrdp-dvc/src/lib.rs, crates/ironrdp-glutin-renderer/Cargo.toml, crates/ironrdp-graphics/Cargo.toml, crates/ironrdp-pdu/Cargo.toml, crates/ironrdp-pdu/README.md, crates/ironrdp-pdu/src/lib.rs, crates/ironrdp-pdu/src/macros.rs, crates/ironrdp-pdu/src/write_buf.rs, crates/ironrdp-rdpdr/src/lib.rs, crates/ironrdp-rdpsnd/src/lib.rs, crates/ironrdp-server/src/display.rs, crates/ironrdp-server/src/handler.rs, crates/ironrdp-session/src/x224/mod.rs, crates/ironrdp-svc/src/lib.rs, crates/ironrdp-testsuite-core/tests/clipboard.rs, crates/ironrdp/Cargo.toml, crates/ironrdp/src/lib.rs
Adds initialization sequence of CLIPRDR static virtual channel
+ Changes `ironrdp-svc` API to accommodate the need for adding SVC PDU flags on a per-message basis
+ Reduces boilerplate code for `AsAny`
Part of #107
=> CLIPRDR(clipboard) processing - initialization sequence

crates/ironrdp-session/src/image.rs
@CBenoit I accidentally discovered I made an oopsie and forgot to remove inappropriate `eprintln!` which was left after pointer rendering implementation, sorry 😨 It somehow slipped through the cracks during self-review & PR
=> Remove redundant debug comment

crates/ironrdp-client/src/config.rs, crates/ironrdp-connector/src/connection.rs, crates/ironrdp-pdu/src/rdp/capability_sets.rs, crates/ironrdp-pdu/src/rdp/capability_sets/general.rs, crates/ironrdp-pdu/src/rdp/capability_sets/general/tests.rs, crates/ironrdp-server/src/capabilities.rs, crates/ironrdp-web/src/session.rs
Allow values outside the range of known values. FreeRDP has been using 0xFFFF - N for custom values.
=> fix(pdu): don't be strict about platform type

crates/ironrdp-async/src/framed.rs, crates/ironrdp-connector/src/lib.rs, crates/ironrdp-futures/src/lib.rs, crates/ironrdp-pdu/src/lib.rs, crates/ironrdp-pdu/src/macros.rs, crates/ironrdp-tokio/src/lib.rs, crates/ironrdp-web/src/session.rs
Using GATs we achieve genericity over Send and Sync marker traits. The `FramedRead` and `FramedWrite` traits can now be used in both single-threaded and multi-threaded contexts.
cc @probakowski @ibeckermayer does it looks good to you?
This is an alternative to https://github.com/Devolutions/IronRDP/pull/188 that is working for both web and native clients.
=> feat: support for both Send and !Send Framed impls

ARCHITECTURE.md, Cargo.lock, Cargo.toml, README.md, crates/ironrdp-async/src/framed.rs, crates/ironrdp-blocking/Cargo.toml, crates/ironrdp-blocking/README.md, crates/ironrdp-blocking/src/connector.rs, crates/ironrdp-blocking/src/framed.rs, crates/ironrdp-blocking/src/lib.rs, crates/ironrdp-blocking/src/session.rs, crates/ironrdp-client/Cargo.toml, crates/ironrdp-client/README.md, crates/ironrdp-client/src/rdp.rs, crates/ironrdp-connector/src/connection.rs, crates/ironrdp-futures/src/lib.rs, crates/ironrdp-svc/src/lib.rs, crates/ironrdp-tls/src/lib.rs, crates/ironrdp-web/src/image.rs, crates/ironrdp/Cargo.toml, crates/ironrdp/examples/screenshot.rs
Adds a blocking I/O higher-level abstraction library: ironrdp-blocking.
It’s equivalent to ironrdp-async, but uses blocking I/O traits from standard library.
=> feat(blocking): initial implementation

Cargo.lock, Cargo.toml, crates/ironrdp-client/Cargo.toml, crates/ironrdp-client/src/config.rs, crates/ironrdp-client/src/rdp.rs, crates/ironrdp-cliprdr/src/lib.rs, crates/ironrdp-fuzzing/Cargo.toml, crates/ironrdp-fuzzing/src/oracles/mod.rs, crates/ironrdp-graphics/src/pointer.rs, crates/ironrdp-graphics/src/rectangle_processing.rs, crates/ironrdp-rdpdr/src/lib.rs, crates/ironrdp-rdpdr/src/pdu/efs.rs, crates/ironrdp-rdpdr/src/pdu/mod.rs, crates/ironrdp-session/src/active_stage.rs, crates/ironrdp-session/src/fast_path.rs, crates/ironrdp-session/src/rfx.rs, crates/ironrdp-session/src/x224/gfx.rs, crates/ironrdp-svc/src/lib.rs, crates/ironrdp-testsuite-core/tests/pdu/pointer.rs
Adds handling for `DR_CORE_SERVER_CLIENTID_CONFIRM` and `DR_CORE_DEVICELIST_ANNOUNCE`/`DR_CORE_DEVICELIST_ANNOUNCE_REQ`, the next steps in the rdpdr initialization sequence.
=> feat(rdpdr): `DR_CORE_SERVER_CLIENTID_CONFIRM` and `DR_CORE_DEVICELIST_ANNOUNCE`

crates/ironrdp-rdpdr/src/pdu/esc.rs
Corresponds with https://github.com/gravitational/teleport/pull/33056
=> `GetStatusChangeCall` and `GetStatusChangeReturn`

crates/ironrdp-connector/src/lib.rs, crates/ironrdp-rdpdr/src/backend/mod.rs, crates/ironrdp-rdpdr/src/pdu/esc.rs, crates/ironrdp-svc/src/lib.rs
As discussed in thread starting here: https://github.com/Devolutions/IronRDP/pull/208#discussion_r1348907988
=> Removes Sync dependency for Sequence and downstream traits

.github/workflows/coverage.yml
The check to disable the coverage job is not working properly.
=> ci: make sure the coverage workflow is disabled for forks

Cargo.lock, crates/ironrdp-cliprdr-native/Cargo.toml, crates/ironrdp-cliprdr-native/src/windows/cliprdr_backend.rs, crates/ironrdp-cliprdr/src/backend.rs, crates/ironrdp-cliprdr/src/lib.rs
Teleport could use this feature, afaik it's harmless and simple to add (we're using `impl_as_any!`).
Corresponds with https://github.com/gravitational/teleport/pull/33506
=> Makes `CliprdrBackend` `AsAny`

crates/ironrdp-client/src/gui.rs, crates/ironrdp-client/src/rdp.rs, crates/ironrdp-session/src/active_stage.rs, crates/ironrdp-session/src/fast_path.rs
This removes some `as` casts that were never required.
=> refactor: use u16 for pointer position

crates/ironrdp-pdu/src/rdp/client_info.rs, crates/ironrdp-rdpdr/src/pdu/efs.rs, crates/ironrdp-rdpdr/src/pdu/esc.rs, crates/ironrdp-rdpdr/src/pdu/esc/rpce.rs, crates/ironrdp-rdpdr/src/pdu/mod.rs
@ibeckermayer you’re right, there were quite a bunch of these!
I ran `sd` commands to change most places, and modified using multi-cursors the last few places it didn’t covered (mainly the places which were not consistent in the first place).
```shell
$ fd --extension=rs --exec sd "/// \[([\d\.]+)( .+)\]:" "/// [\$1]:"
$ fd --extension=rs --exec sd "/// \[([\d\.]+)( .+)\]" "/// [\$1]\$2"
```
=> docs: uniformize links to specification

.github/workflows/npm-publish.yml
Note that I wasn’t able to test the workflow even when specifying the branch:
```shell
$ gh workflow run npm-publish.yml --ref "ci/npm-publish-workflow"
HTTP 404: Not Found (https://api.github.com/repos/Devolutions/IronRDP/actions/workflows/npm-publish.yml)
```
I’ll test once this is merged.
=> ci: add a workflow to publish the npm package

.github/workflows/ci.yml, fuzz/Cargo.lock, xtask/src/check.rs, xtask/src/cli.rs, xtask/src/main.rs
Note that we can’t really use the `--locked` option of cargo, because to run xtask, we need to compile it using cargo, and thus the lock files are already "refreshed" as far as cargo is concerned. Instead, this new task will check for modifications to the lock files using `git-status` porcelain. The side benefit is that we can check for npm lock files too.
=> ci: check for dirty lock files

web-client/iron-remote-gui/package.json, web-client/iron-remote-gui/src/enums/MouseButton.ts, web-client/iron-remote-gui/src/enums/MouseButtonState.ts, web-client/iron-svelte-client/package.json
There's currently an issue with Prettier 3.0 which requires the seemingly redundant --plugin setting. This bug will be fixed in the 3.1, and the extra argument may then be removed.
=> chore(web-client): fix prettier checks

crates/ironrdp-connector/src/license_exchange.rs, crates/ironrdp-connector/src/server_name.rs, crates/ironrdp-fuzzing/src/oracles/mod.rs, crates/ironrdp-pdu/src/rdp/server_license.rs, crates/ironrdp-pdu/src/rdp/server_license/client_new_license_request.rs, crates/ironrdp-pdu/src/rdp/server_license/client_platform_challenge_response.rs, crates/ironrdp-pdu/src/rdp/server_license/licensing_error_message.rs, crates/ironrdp-pdu/src/rdp/server_license/server_license_request.rs, crates/ironrdp-pdu/src/rdp/server_license/server_license_request/cert.rs, crates/ironrdp-pdu/src/rdp/server_license/server_platform_challenge.rs, crates/ironrdp-pdu/src/rdp/server_license/server_upgrade_license.rs
I was not able to reproduce the problem even when using the RDS Lab.
Because of that, I attempted to gut-solve the problem by:
- Expecting a SERVER_LICENSE_ERROR message in the final step of the licensing sequence, handling the STATUS_VALID_CLIENT error code as a success
- Attach additional context to the returned errors
- Log a warning when we receive the STATUS_VALID_CLIENT code at an unexpected place
The rationale is that either the problem is fixed, or we will have more information to troubleshoot otherwise.
Closes #268
Issue: ARC-180
=> fix(connector): always expect STATUS_VALID_CLIENT

STYLE.md
Stole the format from rust-analyzer document:
- https://github.com/rust-lang/rust-analyzer/blob/76633199f4316b9c659d4ec0c102774d693cd940/docs/dev/style.md
It includes IronRDP-specific guidelines I wrote down during code reviews, as well as some guidelines directly copied from the original rust-analyzer document because they were relevant for IronRDP as well.
[Rendered](https://github.com/Devolutions/IronRDP/blob/docs/style.md/STYLE.md).
=> docs: add STYLE.md document

web-client/iron-remote-gui/package-lock.json, web-client/iron-remote-gui/package.json, web-client/iron-remote-gui/public/package.json
Version 0.9.0 of the Web Client includes:
- Fix for https://github.com/Devolutions/IronRDP/issues/268
- Clipboard support :tada: (by @pacmancoder)
=> chore(release): prepare web client for 0.9.0

Cargo.lock, crates/ironrdp-acceptor/src/connection.rs, crates/ironrdp-acceptor/src/finalization.rs, crates/ironrdp-pdu/src/lib.rs, crates/ironrdp-server/Cargo.toml, crates/ironrdp-server/src/server.rs
Fixes #220 
This makes the acceptor accumulate any input events received during connection finalization, so they can be processed before starting the client loop.
Because the FontList is an x224 pdu and input events could be FastPath, I added a new PduHint that matches any pdu.
Also made the acceptor a little more robust and improved logging.
=> acceptor: fix input events during connection finalization

web-client/iron-svelte-client/.eslintrc.yaml
Ignore css files in Eslint process for now. We don't have a lot of css file at this moment and it blocks other PR from merging. 
Eslint will give this error is ./web/iron-svelte-client
```
C:\Users\jou\code\IronRDP\web-client\iron-svelte-client\src\lib\login\login.css
0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/src\lib\login\login.css` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json
The extension for the file (`.css`) is non-standard. It should be added to your existing `parserOptions.extraFileExtensions`
✖ 1 problem (1 error, 0 warnings)
```
=> Ignore *.css in Eslint

web-client/iron-remote-gui/package-lock.json, web-client/iron-remote-gui/package.json, web-client/iron-svelte-client/package-lock.json, web-client/iron-svelte-client/package.json
A bug in 3.0.x versions was causing the --plugin setting to be required in order to let prettier know about svelte. This is now fixed.
=> chore(web-client): bump prettier to 3.1.0

crates/ironrdp-cliprdr-format/src/bitmap.rs
As it turns out we actually support the BI_BITFIELDS compression (which is not actually for compressed bitmaps).
Quote from [MS-WMF] section 2.1.1.7:
> The bitmap is not compressed, and the color table consists of three
> DWORD (defined in [MS-DTYP] section 2.2.9) color masks that specify the
> red, green, and blue components, respectively, of each pixel. This is
> valid when used with 16 and 32-bits per pixel bitmaps.
[dibv5-bitfields-compression.webm](https://github.com/Devolutions/IronRDP/assets/3809077/440695e7-88ce-4d64-96e1-670ec8b5409f)
All I did was to add `BitmapCompression::BITFIELDS` to the `SUPPORTED_COMPRESSION` array, and things just worked out of the box.
@pacmancoder maybe you understand why it works better than me?
=> feat(cliprdr): BI_BITFIELDS compression is supported

STYLE.md, crates/ironrdp-cliprdr-format/README.md, crates/ironrdp-cliprdr-format/src/bitmap.rs, crates/ironrdp-cliprdr-format/src/html.rs, crates/ironrdp-cliprdr-native/src/windows/clipboard_impl.rs, crates/ironrdp-cliprdr-native/src/windows/remote_format_registry.rs, crates/ironrdp-cliprdr/README.md, crates/ironrdp-cliprdr/src/backend.rs, crates/ironrdp-cliprdr/src/pdu/format_list.rs, crates/ironrdp-cliprdr/src/pdu/mod.rs, crates/ironrdp-fuzzing/src/oracles/mod.rs, crates/ironrdp-graphics/src/pointer.rs, crates/ironrdp-pdu/src/rdp/vc/dvc/gfx/graphics_messages.rs, crates/ironrdp-pdu/src/rdp/vc/dvc/gfx/graphics_messages/server.rs, crates/ironrdp-testsuite-core/tests/clipboard/format.rs, crates/ironrdp-web/src/clipboard/mod.rs, web-client/iron-remote-gui/src/iron-remote-gui.svelte
I studied and experimented with cliprdr code over the weekend. Here is some related housekeeping.
Commits are independents and the intention is to rebase-merge them:
- [refactor(cliprdr): fix typos](https://github.com/Devolutions/IronRDP/pull/289/commits/48b8856f4b0033388e7ea10d6365f261fc3a3c99)
- [refactor(web): explain cliprdr web backend quirks](https://github.com/Devolutions/IronRDP/pull/289/commits/575a85fc6bf91de2a5a27d99ab4d5c35556b909a)
- [perf: enable inlining for a few functions](https://github.com/Devolutions/IronRDP/pull/289/commits/773901e379a9b9d657165b82f50ded2b56d38732)
These are very small functions which are used multiple times in the same loop inside cliprdr web backend.
- [style: local helper functions](https://github.com/Devolutions/IronRDP/pull/289/commits/290bf37efae …
=> CLIPRDR housekeeping

crates/ironrdp-pdu/src/cursor.rs, crates/ironrdp-rdpdr/src/lib.rs, crates/ironrdp-rdpdr/src/pdu/efs.rs, crates/ironrdp-rdpdr/src/pdu/mod.rs
- Added a new method write_i8 to WriteCursor in ironrdp-pdu/src/cursor.rs, allowing for writing an 8-bit integer value to the cursor.
- Updated Rdpdr in ironrdp-rdpdr/src/lib.rs to handle an additional case for ClientDriveQueryDirectoryResponse in the error handling logic.
- Introduced several new structures in ironrdp-rdpdr/src/pdu/efs.rs related to directory information, including FileBothDirectoryInformation, FileFullDirectoryInformation, FileNamesInformation, and FileDirectoryInformation.
- Added support for the ClientDriveQueryDirectoryResponse PDU in various parts of ironrdp-rdpdr, including the RdpdrPdu enum and its implementation.
- Added a ServerDriveQueryDirectoryRequest structure to handle server requests for querying directory information, along with the necessary encoding …
=> `DirectoryControl`.`QueryDirectory`

web-client/iron-remote-gui/package-lock.json, web-client/iron-remote-gui/package.json, web-client/iron-remote-gui/public/package.json
The new version of IronRDP web client supports hardware cursors. This can significantly improve perceived performance over slow links.
Demonstration:
[demo-hardware-cursor.webm](https://github.com/Devolutions/IronRDP/assets/3809077/1f895688-edb0-4923-9b10-de5fe32d5a2e)
One difference with the previous implementation is that the cursor style remains unchanged and can go out of the canvas as long as the hotspot remains inside (the point which actually interacts with elements on the screen). Also, the I-beam icon (the cursor icon shown when selecting text) is following a checkered pattern, alternating black and white pixels. This is a compromise so that the cursor is visible even if the background is dark.
cc @pacmancoder
=> chore(release): prepare web client for 0.10.0

crates/ironrdp-rdpdr/src/lib.rs, crates/ironrdp-rdpdr/src/pdu/efs.rs, crates/ironrdp-rdpdr/src/pdu/mod.rs
- Added support for ServerDriveQueryVolumeInformationRequest in the RDPDR EFS module.
- Implemented decoding logic for ServerDriveQueryVolumeInformationRequest with checks for valid FileSystemInformationClassLevels.
- Extended the RdpdrPdu enum to include ClientDriveQueryVolumeInformationResponse.
- Implemented ClientDriveQueryVolumeInformationResponse with appropriate encoding and sizing methods.
- Updated Rdpdr handling to accommodate the new ClientDriveQueryVolumeInformationResponse type.
=> Implement `ServerDriveQueryVolumeInformationRequest` and `ClientDriveQueryVolumeInformationResponse` in RDPDR

web-client/iron-remote-gui/vite.config.ts
Fixes the broken package 0.11.0, as rxjs is excluded as umd js, but our project all includes rxjs as module. Wrap rxjs back into the umd js defination, so it operates. This is temporary solution, as umd js causes larger bundles size and optimization slow down. in fact, we cannot use the exported enum value, as our TS is in module js format, but our actual js is not module, hence, we can only export types not any values.
but anyway, it works for now.
=> Fix broken Package 0.11.0, bundle Rxjs back into umd.js 

web-client/iron-remote-gui/package-lock.json, web-client/iron-remote-gui/package.json
Fixed broken 0.11.0 package for rxjs dependency issue
=> chore(release): prepare iron-remote-gui for 0.11.1

Cargo.lock, Cargo.toml, crates/ironrdp-cliprdr/Cargo.toml, crates/ironrdp-graphics/Cargo.toml, crates/ironrdp-pdu/Cargo.toml, crates/ironrdp-pdu/src/cursor.rs, crates/ironrdp-rdpdr/Cargo.toml, crates/ironrdp-rdpdr/src/lib.rs, crates/ironrdp-rdpdr/src/pdu/efs.rs, crates/ironrdp-rdpdr/src/pdu/mod.rs, crates/ironrdp-session/Cargo.toml, crates/ironrdp-svc/Cargo.toml, fuzz/Cargo.lock
`SetInformation` is straightforward.
`UnsupportedMinorFunctionRequest` because I realized that the server is liable to send us back an occasional `NotifyChangeDirectory` or `None` which we want to handle. This allows us to handle these cases gracefully (but without writing all the decode/encode logic), and kicks the handling up the stack to the `RdpdrBackend` implementer (Teleport in our case). Teleport simply mimics what [FreeRDP currently does with these](https://github.com/FreeRDP/FreeRDP/blob/511444a65e7aa2f537c5e531fa68157a50c1bd4d/channels/drive/client/drive_main.c#L660-L666).
=> `SetInformation` and `UnsupportedMinorFunctionRequest`

crates/ironrdp-pdu/src/cursor.rs, crates/ironrdp-pdu/src/lib.rs, crates/ironrdp-pdu/src/macros.rs, crates/ironrdp-rdpdr/src/lib.rs, crates/ironrdp-rdpdr/src/pdu/efs.rs, crates/ironrdp-rdpdr/src/pdu/mod.rs
- Add a new `UnsupportedPdu` kind to `PduError`, enhancing error handling capabilities in ironrdp-pdu. This new error kind allows for more specific error messages when encountering unsupported PDUs.
- Implement a macro `unsupported_pdu_err` for conveniently creating `PduError` instances with the `UnsupportedPdu` kind.
- Implement handling for `ServerDriveLockControlRequest` in ironrdp-rdpdr, including the definition of the struct and its decoding method. This adds support for processing lock control requests in the RDPDR protocol.
- Update `Rdpdr`'s `process` method to utilize the new `unsupported_pdu_err` when encountering unknown packet IDs, replacing the previous handling of unimplemented PDUs.
- Remove the `Unimplemented` variant from `RdpdrPdu` and `Component` enums, replacing it …
=> `LockControl`

crates/ironrdp-cliprdr/src/pdu/capabilities.rs, crates/ironrdp-pdu/src/basic_output/bitmap/rdp6.rs, crates/ironrdp-pdu/src/macros.rs, crates/ironrdp-rdpdr/src/pdu/efs.rs, crates/ironrdp-rdpdr/src/pdu/esc.rs, crates/ironrdp-rdpdr/src/pdu/esc/rpce.rs, crates/ironrdp-rdpdr/src/pdu/mod.rs, crates/ironrdp-testsuite-core/tests/pcb.rs
@zmb3 suggested we add this for Teleport to avoid copy-paste errors wherever we're using these macros, however it occurred to me that this might best fit as a more general solution throughout IronRDP.
I tested this by applying the following patch
<details>
```patch
diff --git a/crates/ironrdp-cliprdr/src/pdu/capabilities.rs b/crates/ironrdp-cliprdr/src/pdu/capabilities.rs
index 508b4e5..34381af 100644
--- a/crates/ironrdp-cliprdr/src/pdu/capabilities.rs
+++ b/crates/ironrdp-cliprdr/src/pdu/capabilities.rs
@@ -166,10 +166,10 @@ impl<'de> PduDecode<'de> for CapabilitySet {
let _length = src.read_u16();
match caps_type {
-            Self::CAPSTYPE_GENERAL => {
-                let general = GeneralCapabilitySet::decode(src)?;
-                Ok(Self::General(general))
-            }
+ …
```
=> refactor: function! macro for error context

crates/ironrdp-tls/Cargo.toml, crates/ironrdp-tls/README.md, crates/ironrdp-tls/src/lib.rs, crates/ironrdp-tls/src/native_tls.rs, crates/ironrdp-tls/src/rustls.rs, crates/ironrdp-tls/src/stub.rs
FYI @ibeckermayer 
I remember you added the default feature in https://github.com/Devolutions/IronRDP/pull/144
But I think I prefer to revert to not having any default feature for `ironrdp-tls`, and deliberately keep it unusable when no feature is enabled.
The motivation is now described in the README.md of the crate.
Some context on why I decided to reconsider this: https://github.com/Devolutions/IronRDP/issues/314#issuecomment-1840411852
I myself had to think twice when investigating.
=> refactor: clarify features exposed by ironrdp-tls

crates/ironrdp-connector/src/channel_connection.rs, crates/ironrdp-connector/src/connection.rs
For context: https://github.com/Devolutions/IronRDP/issues/314#issuecomment-1844871275
=> fix(connector): better errors for MCS channel confirm

crates/ironrdp-async/src/connector.rs, crates/ironrdp-blocking/src/connector.rs, crates/ironrdp-client/src/config.rs, crates/ironrdp-connector/src/connection.rs, crates/ironrdp-connector/src/credssp.rs, crates/ironrdp-connector/src/lib.rs, crates/ironrdp-pdu/src/macros.rs, crates/ironrdp-pdu/src/nego.rs, crates/ironrdp-pdu/src/rdp/suppress_output.rs, crates/ironrdp-testsuite-core/src/core_data.rs, crates/ironrdp-testsuite-core/tests/pdu/x224.rs, crates/ironrdp-web/src/session.rs, crates/ironrdp/examples/screenshot.rs
Replace the bitflag-based connector config API with a boolean-based one:
- `enable_tls`: set the PROTOCOL_SSL flag
- `enable_credssp`: set the PROTOCOL_HYBRID and PROTOCOL_HYBRID_EX flags
NLA can be enforced on client-side with `enable_tls = false`  + `enable_credssp = true`.
The `--security_protocol` argument was removed from the native client CLI, and instead it’s possible to disable specific protocols with `--no-tls` and `--no-credssp`. By default, both protocols are enabled for maximum compatibility with most RDP servers. We may change the defaults in the future.
For additional background on this change, see [this comment](https://github.com/Devolutions/IronRDP/issues/314#issuecomment-1843925374).
cc @awakecoding @thenextman 
FYI @ibeckermayer 
In your case, you’ll have to set …
=> fix(connector): better security protocol selection

crates/ironrdp-client/src/config.rs, crates/ironrdp-client/src/main.rs, crates/ironrdp-server/src/server.rs
Logging to a file by default isn't common.
Use a more verbose, colorful and developer-friendly format in this case.
It would be nice to move setup_logging() in some common place, for other binaries.
=> feat(client): log to stdout/err by default

crates/ironrdp-session/src/fast_path.rs, crates/ironrdp-session/src/image.rs, crates/ironrdp-session/src/utils.rs
This fixes the compability with the server example.
=> feat(session): handle surface with codec ID 0 (raw bitmap)

crates/ironrdp-client/src/gui.rs, crates/ironrdp-client/src/rdp.rs, crates/ironrdp-pdu/src/mcs.rs, crates/ironrdp-pdu/src/rdp/headers.rs, crates/ironrdp-session/src/active_stage.rs, crates/ironrdp-session/src/lib.rs, crates/ironrdp-session/src/x224/mod.rs, crates/ironrdp-web/src/session.rs, crates/ironrdp/examples/screenshot.rs, web-client/iron-remote-gui/src/services/wasm-bridge.service.ts, xtask/src/wasm.rs
This PR implements graceful disconnect support.
Closes #115
=> feat(session): graceful disconnection support

crates/ironrdp-client/src/network_client.rs, crates/ironrdp-web/src/network_client.rs
The HTTP client was ignoring the status code of the HTTP response received from the KDC proxy (Devolutions Gateway), and provided sspi-rs with an empty payload, resulting in the "TruncatedData" error.
Previous error:
```
[CredSSP] CredSSP Caused by: InvalidToken: ASN1 DER error: TruncatedData
```
New error:
```
[KdcProxy] reason: HTTP status error (500 Internal Server Error)
```
Issue: https://devolutions.atlassian.net/browse/DPS-9810
=> fix(credssp): catch KDC proxy HTTP status error

crates/ironrdp-connector/src/channel_connection.rs
=> fix(connector): send join requests in a single batch

web-client/iron-remote-gui/src/services/wasm-bridge.service.ts
Since [this patch](https://github.com/Devolutions/IronRDP/pull/364) from @ibeckermayer, we support sending the real meta key scancode. This patch is modifying the web component so that we now actually send it instead of using the shortcut for the window menu.
=> fix(web): send the actual meta key scancode

crates/ironrdp-futures/src/lib.rs, crates/ironrdp-tokio/src/lib.rs, crates/ironrdp-web/src/session.rs
For non-Send types, the common terminology is "Local", or "Thread Local" instead of "Single Threaded".
This patch is renaming such types since this is shorter and standard.
=> refactor(async): use the "Local" terminology

web-client/iron-remote-gui/src/services/wasm-bridge.service.ts
Fix for the following error message spam in `ironrdp-web`
=> fix(web): set correct `src` for cursor proxy `Image` object

crates/ironrdp-session/src/legacy.rs
Previously, when encoding DVC messages we didn't set length correctly - `dvc::ClientPdu` and `DvcData` was not included. That led to broken stream and errors.
This PR fixes that by creating additional wrapper (`DvcMessage`) that is encoded with all constituents included.
=> Fix DVC message length

crates/ironrdp-acceptor/src/channel_connection.rs, crates/ironrdp-acceptor/src/connection.rs, crates/ironrdp-connector/src/channel_connection.rs, crates/ironrdp-connector/src/connection.rs
Closes #165
Added support for `RNS_UD_CS_SUPPORT_SKIP_CHANNELJOIN` on both client and server.
I implemented it according to (my best understanding of) the spec, however I couldn't get the windows rdp server to actually send the flag to verify it.
I guess I could try to validate the server implementation using a freerdp client instead.
Let me know if you guys have any suggestions for making sure this is working properly :)
=> feat: add support for skip channel join flag

crates/ironrdp-rdpdr/src/pdu/efs.rs, crates/ironrdp-rdpdr/src/pdu/esc.rs, crates/ironrdp-session/src/legacy.rs
Also includes a custom `PartialEq` implementation for `DeviceControlResponse`, ~and removes `std::io::Error::other` which appears to be a nightly-only feature for now~.
=> fix(rdpdr): implement `Clone` and `PartialEq` on most of efs and esc

fuzz/Cargo.lock
Currently, the fuzzer uses a `png` package with the old version `0.17.11`, while the main build runs the latest `0.17.13`.
Version `0.17.11` is affected by several reproducible issues, such as https://github.com/image-rs/image-png/pull/445 or https://github.com/image-rs/image-png/issues/461. This commit updates all dependencies for the fuzzer.
=> test(fuzz): update dependencies

crates/ironrdp-pdu/src/ber.rs, crates/ironrdp-pdu/src/gcc/security_data.rs, crates/ironrdp-pdu/src/rdp/server_license/client_platform_challenge_response.rs, crates/ironrdp-pdu/src/rdp/server_license/server_license_request/cert.rs
This PR fixed failing fuzzing on master
=> fix(fuzz): fix failing fuzzing after pdu encode/decode refactoring

Cargo.toml, crates/ironrdp-acceptor/src/lib.rs, crates/ironrdp-async/src/connector.rs, crates/ironrdp-async/src/framed.rs, crates/ironrdp-client/src/rdp.rs, crates/ironrdp-connector/src/connection.rs, crates/ironrdp-connector/src/connection_activation.rs, crates/ironrdp-connector/src/connection_finalization.rs, crates/ironrdp-connector/src/legacy.rs, crates/ironrdp-connector/src/lib.rs, crates/ironrdp-graphics/Cargo.toml, crates/ironrdp-pdu/Cargo.toml, crates/ironrdp-pdu/src/codecs/rfx.rs, crates/ironrdp-pdu/src/codecs/rfx/data_messages.rs, crates/ironrdp-pdu/src/codecs/rfx/header_messages.rs, crates/ironrdp-pdu/src/rdp/capability_sets.rs, crates/ironrdp-pdu/src/rdp/headers.rs, crates/ironrdp-pdu/src/rdp/vc/dvc/display.rs, crates/ironrdp-session/src/active_stage.rs, crates/ironrdp-session/src/rfx.rs, crates/ironrdp-session/src/x224/mod.rs, crates/ironrdp-web/src/session.rs
The [Deactivate All PDU](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/8a29971a-df3c-48da-add2-8ed9a05edc89)  is sent from server to client to indicate that the connection will be dropped or that a capability re-exchange using a [Deactivation-Reactivation Sequence](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/dfc234ce-481a-4674-9a5d-2a7bafb14432) will occur.
In practice, this happens when a screen resize is requested. When this PDU is received by the client, it is meant to begin executing the Deactivation-Reactivation Sequence, which is the Capability Exchange and Connection Finalization phases of the connection sequence.
What this PR does is
1. Break out the Capability Exchange and Connection Finalization phases of the connection …
=> feat: support for `Server Deactivate All PDU`

crates/ironrdp-client/src/config.rs, crates/ironrdp-connector/src/connection.rs, crates/ironrdp-connector/src/lib.rs, crates/ironrdp-pdu/src/rdp/client_info.rs, crates/ironrdp-testsuite-core/tests/pcb.rs, crates/ironrdp-web/src/session.rs, crates/ironrdp/examples/screenshot.rs
Adds performance flags to the `connector::Config`.
Also adds a Default impl for PerformanceFlags. Teleport requires this in order to optionally use a non-default performance flag based on our user config.
=> feat: configurable performance flags

crates/ironrdp-cliprdr-native/src/lib.rs, crates/ironrdp-cliprdr-native/src/stub.rs, crates/ironrdp-cliprdr/src/lib.rs, crates/ironrdp-cliprdr/src/pdu/format_data/mod.rs, crates/ironrdp-server/Cargo.toml, crates/ironrdp-server/src/builder.rs, crates/ironrdp-server/src/clipboard.rs, crates/ironrdp-server/src/lib.rs, crates/ironrdp-server/src/server.rs, crates/ironrdp/examples/server.rs
The clipboard factory/backend alone isn't enough to send back or notify of messages, adopt a similar approach as the client, using a channel to dispatch and send messages from the server loop.
(ideally, I wish the channel implementation details wouldn't be handled by the main loop, but this has pros and cons, so let's just follow the client approach for now)
=> server: add ServerEvent for clipboard

crates/ironrdp-rdpdr/src/pdu/esc.rs, crates/ironrdp-rdpdr/src/pdu/esc/ndr.rs, crates/ironrdp-rdpdr/src/pdu/esc/rpce.rs
Adds handling for the ascii variants of the currently support smartcard calls.
A couple of Teleport users have encountered these in the wild, and one of them tested this implementation.
=> feat: scard ascii variants

crates/ironrdp-connector/src/connection_activation.rs
This change fixes cursor rendering in Windows 2019 and older.
Previously only text cursor was rendered, all others defaulted to native cursor from client.
Set of flags matches what is used in [FreeRDP](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/core/settings.c#L541)
=> fix(connector): fix cursor rendering in Windows 2019

.gitignore, ffi/dotnet/Devolutions.IronRdp.ConnectExample/Devolutions.IronRdp.ConnectExample.csproj, ffi/dotnet/Devolutions.IronRdp.ConnectExample/Program.cs, ffi/dotnet/Devolutions.IronRdp/Devolutions.IronRdp.csproj, xtask/src/ffi.rs, xtask/src/main.rs
First step in building FFI, allow it to be used simply by `dotnet add package` command by our consumers without worrying about loading the .dll
Only support windows x64 for now, and used solely in local development, not suppose to be pushed to any Nuget registry.
Other platform support will be added later.
---
step to build and publish
1. run `cargo xtask ffi bindings` and `cargo xtask ffi build --release` in IronRdp project root
2. (optional) remove the /bin/ directory under `Devolutions.IronRdp` 
3. run `dotnet build -r  win-x64` to build the dotnet project as well as packages it
4. run `dotnet nuget push ".\bin\Release\Devolutions.IronRdp.{version}.nupkg" --source "{your_local_nuget_server_source}"`
the other end can download with 
`dotnet add package "Devolutions.IronRdp" --source …
=> chore(ffi):allow Devolutions.IronRdp to be build and packed with Nuget with the dll on Windows

ffi/dotnet/Devolutions.IronRdp/src/Connection.cs
Dotnet TLS cache/resume will lead to failure of RDP connections at the second time to the same server. Specific reason see this thread (I don't understand completely, but it fixes the problem)
https://github.com/dotnet/runtime/issues/78305#issuecomment-1315342177
=> fix(dotnet): disable dotnet TLS cache/resume

crates/ironrdp-pdu/src/rdp/server_license/licensing_error_message.rs
According to
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/73170ca2-5f82-4a2d-9d1b-b439f3d8dadc
wMsgSize is "the size in bytes of the licensing packet (including the size of the preamble)". It must thus exclude BASIC_SECURITY_HEADER_SIZE.
Fixes mstsc connection to IronRDP server/acceptor.
Fixes 5c42ade597fa442 ("fix: make license parsing and protocol more resilient (#436)")
=> fix(pdu): fix preamble_size in LicensingErrorMessage regression

ffi/dotnet/Devolutions.IronRdp.AvaloniaExample/MainWindow.axaml.cs, ffi/dotnet/Devolutions.IronRdp.AvaloniaExample/Program.cs, ffi/dotnet/Devolutions.IronRdp/Generated/DiplomatRuntime.cs, ffi/dotnet/Devolutions.IronRdp/src/ClientConnector.Addons.cs, ffi/dotnet/Devolutions.IronRdp/src/Connection.cs, ffi/dotnet/Devolutions.IronRdp/src/ConnectionActivationSequence.Addons.cs, ffi/dotnet/Devolutions.IronRdp/src/ISequence.cs
It’s possible to implement interfaces even on FFI types, because they are declared as partials.
```csharp
public partial class MySequence : ISequence {}
```
So long as the type exposes the required functions, this one-liner is enough.
cc @irvingoujAtDevolution
=> refactor(ffi): ISequence interface for sequences

.github/workflows/nuget-publish.yml
Avoiding macos-13 and macos-14 for now, as it requires selecting an Intel or Apple Silicon runner.
=> ci: update macos runner version

crates/ironrdp-session/src/x224/mod.rs
This message doesn't require a response of any kind, but handling it here will prevent an unknown PDU error which kills the session.
=> Handle the set keyboard indicators PDU

Cargo.lock, crates/ironrdp-client/src/config.rs
Updated the following packages in the `Cargo.lock` file to address dependabot alerts.
whoami `1.4.1` to `1.5.1`
h2 `0.3.23` to `0.3.26`
curve25519-dalek `4.1.1` to `4.1.3`
mio `0.8.10` to `0.8.11`
The following alerts are addressed : 
https://github.com/Devolutions/IronRDP/security/dependabot/56
https://github.com/Devolutions/IronRDP/security/dependabot/65
https://github.com/Devolutions/IronRDP/security/dependabot/66
https://github.com/Devolutions/IronRDP/security/dependabot/60
https://github.com/Devolutions/IronRDP/security/dependabot/65
https://github.com/Devolutions/IronRDP/security/dependabot/72
Code change : 
`whoami::hostname()` is deprecated and was replaced by `fallible::hostname()`. Note that the old function returned the hostname in lowercase but the new one preserves the …
=> chore(deps): update cargo.lock

.github/workflows/ci.yml, Cargo.lock, crates/ironrdp-client/Cargo.toml, crates/ironrdp-server/Cargo.toml, crates/ironrdp-tls/Cargo.toml, crates/ironrdp-tls/src/lib.rs, crates/ironrdp-tls/src/rustls.rs, crates/ironrdp/Cargo.toml, crates/ironrdp/examples/screenshot.rs, crates/ironrdp/examples/server.rs
To remove the duplicate dependencies, we’ll need to release new versions for picky and sspi.
=> chore(deps): update rustls dependency

.github/workflows/ci.yml, crates/ironrdp-client/src/rdp.rs
GitHub considers skipped jobs as fulfilling requirements when merging pull requests. We need to ensure that the success job fails if any previous job has failed.
=> ci: fix success job

.github/workflows/nuget-publish.yml
The Android 19 toolchain is not included anymore, so we bump the minimum supported version to Android 21 for i686 (x86) architecture as well (was already Android 21 everywhere else).
=> ci(nuget-publish): fix build for Android

crates/ironrdp-client/src/rdp.rs
Let TcpStream::connect() handle address resolution, so that multiple addresses (typically localhost -> ipv4 127.0.0.1 or ipv6 ::1) are attempted.
=> fix(client): let address resolve to either ipv4 or ipv6

Cargo.lock, Cargo.toml, crates/ironrdp-client/Cargo.toml, crates/ironrdp-client/src/app.rs, crates/ironrdp-client/src/gui.rs, crates/ironrdp-client/src/lib.rs, crates/ironrdp-client/src/main.rs, crates/ironrdp-cliprdr-native/Cargo.toml, crates/ironrdp-cliprdr-native/src/windows.rs, crates/ironrdp-cliprdr-native/src/windows/clipboard_data_ref.rs, crates/ironrdp-cliprdr-native/src/windows/clipboard_impl.rs, crates/ironrdp-cliprdr-native/src/windows/cliprdr_backend.rs, crates/ironrdp-cliprdr-native/src/windows/os_clipboard.rs, crates/ironrdp-cliprdr-native/src/windows/utils.rs, crates/ironrdp-graphics/src/pointer.rs, crates/ironrdp-web/Cargo.toml, crates/ironrdp-web/src/canvas.rs, ffi/Cargo.toml, ffi/src/clipboard/mod.rs, ffi/src/clipboard/windows.rs
Update code to winit 0.30, various large refactoring necessary.
Related fixes.
My main motivation was fixeing a crash on wayland with HiDPI, and also use update to latest crates.
Fixes:  #375
Fixes:  #521
Fixes:  #522
=> refactor(client): bump to winit 0.30 & fixes

crates/ironrdp-client/src/app.rs, crates/ironrdp-client/src/rdp.rs
Fixes a few issues with resize handling.
=> Client resize improvements

crates/ironrdp-acceptor/src/connection.rs, crates/ironrdp-displaycontrol/src/server.rs, crates/ironrdp-pdu/src/basic_output/surface_commands.rs, crates/ironrdp-server/src/display.rs, crates/ironrdp-server/src/encoder/mod.rs, crates/ironrdp-server/src/encoder/rfx.rs, crates/ironrdp-server/src/server.rs, crates/ironrdp-session/src/image.rs, crates/ironrdp/examples/server.rs
Add deactivation-reactivation support to the server.
Add BitmapUpdate "stride" support, which helps/fixes qemu-rdp server for odd dimensions.
=> Server "resize" support

crates/ironrdp-acceptor/src/connection.rs, crates/ironrdp-server/src/server.rs
Applying suggestions from https://github.com/Devolutions/IronRDP/pull/530
cc @elmarco
=> refactor: follow up to PR 530

crates/ironrdp-acceptor/src/lib.rs, crates/ironrdp-async/src/connector.rs, crates/ironrdp-async/src/framed.rs, crates/ironrdp-blocking/src/connector.rs, crates/ironrdp-blocking/src/framed.rs, crates/ironrdp-client/src/rdp.rs, crates/ironrdp-connector/src/credssp.rs, crates/ironrdp-glutin-renderer/src/draw.rs, crates/ironrdp-pdu/src/basic_output/bitmap.rs, crates/ironrdp-pdu/src/lib.rs, crates/ironrdp-server/src/encoder/bitmap.rs, crates/ironrdp-server/src/server.rs, crates/ironrdp-web/src/session.rs, ffi/dotnet/Devolutions.IronRdp/Generated/RawPduHint.cs, ffi/src/connector/mod.rs
I forgot to squash BitmapEncoder support in #530.
The main part is handling pending incoming client message during deact-react;  queuing and replaying them after acceptation.
=> Server resize follow-up

crates/ironrdp-session/src/active_stage.rs, crates/ironrdp-session/src/x224/mod.rs, ffi/src/session/mod.rs
> The Set Error Info PDU is sent as a precursor to a server-side
disconnect and informs the client of the reason for the disconnection
which will follow. Once this PDU has been processed, the client MUST
store the error code so that the reason for the server disconnect
which will follow can be accurately reported to the user.
=> Save the disconnect reason from the set error info PDU

crates/ironrdp-async/src/framed.rs, crates/ironrdp-client/src/rdp.rs, crates/ironrdp-server/src/encoder/mod.rs, crates/ironrdp-server/src/server.rs, crates/ironrdp-tokio/src/lib.rs, crates/ironrdp-web/src/session.rs
The current server implementation processes events one at a time.
This creates issues when doing large IO or CPU intensive task, such as rfx encoding of large surfaces.
This series split read & write halfes, so they can be processed in parallel. It moves bitmap encoding to a blocking task thread, and finally processes the various server tasks concurrently, rather than via one tokio:select!() branch at a time. 
This makes qemu-rdp a lot more usable under some stressing conditions (playing video, large screen etc)
=> Improve server responsiveness & usability

crates/now-proto-pdu/src/core/mod.rs, crates/now-proto-pdu/src/message.rs
Minor fix in `NowProto` to allow separate decoding of header and message body
=> fix(now-proto): expose NowProto::decode_from_body

Cargo.lock, Cargo.toml, crates/ironrdp-acceptor/src/connection.rs, crates/ironrdp-acceptor/src/credssp.rs, crates/ironrdp-acceptor/src/lib.rs, crates/ironrdp-connector/Cargo.toml, crates/ironrdp-connector/src/lib.rs, crates/ironrdp-core/src/encode.rs, crates/ironrdp-pdu/src/basic_output/fast_path.rs, crates/ironrdp-pdu/src/rdp/client_info.rs, crates/ironrdp-pdu/src/rdp/headers.rs, crates/ironrdp-rdpdr-native/src/lib.rs, crates/ironrdp-rdpdr-native/src/nix/backend.rs, crates/ironrdp-rdpsnd/src/client.rs, crates/ironrdp-rdpsnd/src/server.rs, crates/ironrdp-server/Cargo.toml, crates/ironrdp-server/src/builder.rs, crates/ironrdp-server/src/server.rs, crates/ironrdp/examples/server.rs, crates/now-proto-pdu/src/lib.rs, rust-toolchain.toml
Modify Acceptor to take optionally Credentials at construct time.
The credentials can be changed via ServerEvent::SetCredentials.
Unauthorized connections are no longer accepted.
However, I don't know how to report the error to the client correctly. For now it returns a SetErrorInfo/DeniedConnection, but that doesn't seem appropriate during the connection sequence.
=> feat(server): credentials (with credssp)

crates/ironrdp-acceptor/src/connection.rs
The spec says we should have "the" selected protocol, and mstsc expects that.
=> fix(server): pick one selected protocol

ffi/Cargo.toml
This feature used to be enabled by default, but it's not anymore.
=> build(ffi): enable required feature from ironrdp

Cargo.lock, Cargo.toml, crates/ironrdp-bench/Cargo.toml, crates/ironrdp-bench/benches/bench.rs, crates/ironrdp-graphics/src/color_conversion.rs, crates/ironrdp-graphics/src/dwt.rs, crates/ironrdp-server/Cargo.toml, crates/ironrdp-server/src/encoder/mod.rs, crates/ironrdp-server/src/encoder/rfx.rs, crates/ironrdp-server/src/lib.rs, crates/ironrdp-server/src/server.rs, crates/ironrdp-testsuite-core/tests/graphics/color_conversion.rs
- introduce rfx encoding benchmark with criterion
- speed up a bit DWT with const generics
- use rayon to parallel encode each tile
- speed up a bit rgb->yuv conversion
Unfortunately, it's not simple to use hand-written assembly from a project like yuvutils, because RDP uses odd bias and precision. Something left for the another day.
=> Speed up RemoteFX encoding

.gitignore, docs/NOW-spec.md
Somehow NOW-proto docs gone missing in `devolutions-gateway` repository 🤔 
I restored last docs state from https://github.com/Devolutions/devolutions-gateway/pull/913 (thank god GitHub keeps raw files from PRs)
Now, that `now-proto` crate has been moved to IronRDP in https://github.com/Devolutions/devolutions-gateway/pull/941/files , we could place documentation in IronRDP repo instead.
=> docs(now-proto): add missing NOW-PROTO docs

crates/ironrdp-client/src/config.rs, crates/ironrdp-connector/src/connection.rs, crates/ironrdp-connector/src/lib.rs, crates/ironrdp-web/src/session.rs, crates/ironrdp/examples/screenshot.rs, ffi/src/connector/config.rs
The previous code would (correctly) set a cookie containining the username, but only when using username/password credentials. When smart card credentials are used, the cookie would always contain the empty string.
=> feat(connector): allow clients to specify the x224 nego request data

Cargo.toml, crates/ironrdp/Cargo.toml, crates/ironrdp/README.md, crates/ironrdp/src/lib.rs
Using the top-level README.md of the repository is not ideal.
1/ It contains many information unrelated to the meta crate itself.
2/ The following attribute:
```
#![doc = include_str!("../../../README.md")]
```
will fail at finding the README.md when built via `cargo package`.
=> docs(ironrdp): README.md dedicated to the meta crate

crates/ironrdp-core/src/macros.rs, crates/ironrdp-pdu/src/lib.rs, crates/ironrdp-pdu/src/macros.rs, crates/ironrdp-svc/src/lib.rs
Teleport is generating many errors when using the latest IronRDP crates.
This patch is re-exporting a few items from ironrdp_core so it’s easier for them to incrementally migrate to the newer versions.
=> fix: add a few temporary, hidden re-exports for Teleport

crates/ironrdp-session/src/fast_path.rs
When we hit `Last` fragmentation PDU and there was no `First` before `unwrap` will cause panic.
With this change we will simply skip invalid/incomplete frames the same way we do when we encounter `Single` after `First` or `Next` without `Last`.
=> fix(session): avoid panics when First fragmentation is missing

.github/workflows/release-crates.yml, release-plz.toml
Overlooked the usage change when we switched to the Devolutions-managed action.
=> ci(release-crates): fix usage of release-plz action

crates/ironrdp-core/src/cursor.rs
This was causing a false-positive in cargo-semver-checks:
- https://github.com/obi1kenobi/cargo-semver-checks/issues/1042
=> refactor(core): rename private macro in cursor module

.github/workflows/release-crates.yml
We also need to update the Cargo.lock found in the fuzz folder:
Waiting for https://github.com/Devolutions/actions-public/pull/3
=> ci(release-crates): also update fuzz/Cargo.lock

crates/ironrdp/examples/server.rs
The rt-multi-thread feature of tokio is not enabled when compiling the example alone (without feature unification from other crates of the workspace).
=> docs(ironrdp): fix server example

cliff.toml, release-plz.toml
- Only create release PR for features, bug fixes, documentation updates, build and dependencies changes, and performance improvements.
- Only create GitHub releases for ironrdp and ironrdp-client crates.
- Enable the rustls feature flag when publishing ironrdp-tls, otherwise the compilation will errors out.
=> chore: update release-plz.toml configuration file

release-plz.toml
Pass `--no-verify` to `cargo publish` when publishing `*-native` crates.
`*-native` crates may have all kinds of system requirements depending on the platform. We can only check for the current platform when cargo publish is invoked, all the others are effectively unverified. For this reason, it's not worth complexifying the release-crates.yml workflow. We already verify all targets properly in the CI.
=> chore(tools): update release-plz.toml

xtask/src/bin_version.rs, xtask/src/wasm.rs
https://github.com/WebAssembly/wabt/releases/download/1.0.33/wabt-1.0.33-macos-14.tar.gz is now 404.
=> build(xtask): bump wabt to 1.0.36

crates/ironrdp-rdpsnd/src/server.rs, crates/ironrdp-server/src/server.rs
Add server messages and API to support setting client volume.
=> feat(server): add volume support

Cargo.lock, crates/ironrdp/Cargo.toml, crates/ironrdp/examples/server.rs, crates/ironrdp/src/lib.rs
Demonstrates Opus audio codec support (and also fixes sine wave phase)
=> feat(example): encode audio with Opus

crates/ironrdp-connector/src/license_exchange.rs
This fixes commit dd221bf ("feat: support license caching (#634)") and semver-checks is now happy:
type ProcessorOutput is no longer UnwindSafe, in /tmp/.tmppi9kAf/IronRDP/crates/ironrdp-session/src/x224/mod.rs:15
=> fix(connector): make LicenseCache RefUnwindSafe

Cargo.toml
Replacing deprecated '/' operator in SPDX license expression with 'OR' https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/#d42-disjunctive-or-operator
=> fix: use 'OR' for SPDX license expression

crates/ironrdp-cliprdr-native/src/windows/clipboard_impl.rs
This PR adds handling of `WM_ACTIVATEAPP` in `clipboard_subproc`. Previously, the function handled only `WM_ACTIVATE`. MSDN references:
* WM_ACTIVATE: https://learn.microsoft.com/ru-ru/windows/win32/inputdev/wm-activate ( WM_ACTIVATEAPP: https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-activateapp As you can see from the general description they are quite similar.
During the tests, I was only receiving `WM_ACTIVATEAPP.` To investigate the issue I went to see how Windows handles them. I found that Windows just straight-up handles those messages as they are the same:
* https://github.com/tongzx/nt5src/blob/daad8a087a4e75422ec96b7911f1df4669989611/Source/XPSP1/NT/shell/comctl32/v6/prsht.c#L3873-L3887
* https://github.com/tongzx/nt5src/blob/daad8a087a4e75422ec96b7911f1df4669989611/Sou …
=> fix(cliprdr-native): handle `WM_ACTIVATEAPP` in `clipboard_subproc`

crates/ironrdp-pdu/src/basic_output/fast_path.rs, crates/ironrdp-pdu/src/basic_output/fast_path/tests.rs
The minimal_size() logic didn't properly take into account the overall PDU size.
This fixes random error/disconnect in client.
=> fix(pdu): fix FastPathHeader minimal size

crates/ironrdp-client/src/app.rs
After resize event is sent, we should switch back to a normal mode, instead of wait-duration(0)/polling.
=> fix(client): set back control flow to wait

crates/ironrdp-pdu/src/codecs/rfx.rs, crates/ironrdp-pdu/src/codecs/rfx/header_messages.rs, crates/ironrdp-server/src/encoder/rfx.rs, crates/ironrdp-session/src/rfx.rs, crates/ironrdp-testsuite-core/tests/pdu/rfx.rs
According to the specification, the value does not need to be in the range: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdprfx/4060f07e-9d73-454d-841e-131a93aca675
(the ironrdp-server can send larger values)
=> fix(pdu): TS_RFX_CHANNELT width/height SHOULD be within range

release-plz.toml
Creating a new GitHub release for the ironrdp crate is actually not very relevant.
=> chore: only publish GitHub releases for ironrdp-client

Cargo.lock, ffi/Cargo.toml, ffi/README.md, xtask/src/bin_version.rs, xtask/src/cli.rs, xtask/src/ffi.rs, xtask/src/main.rs
Two commits:
- Adds `cargo xtask ffi install` task for installing the correct version of `diplomat-tool`, in the local root.
- Documents how to build the .NET bindings and the examples.
I noticed the examples were broken. Future work includes: fixing the examples and extending the CI to check the compilation of the .NET examples.
=> docs(ffi): document how to build the .NET bindings

.github/workflows/ci.yml, ffi/dotnet/Devolutions.IronRdp.AvaloniaExample/Devolutions.IronRdp.AvaloniaExample.csproj, ffi/dotnet/Devolutions.IronRdp.AvaloniaExample/MainWindow.axaml.cs, ffi/dotnet/Devolutions.IronRdp.ConnectExample/Program.cs
Fixes compilation of .NET examples in the first commit, and adds CI checks in the second commit.
=> docs(ffi): fix compilation of examples

web-client/iron-remote-gui/src/iron-remote-gui.svelte, web-client/iron-svelte-client/src/lib/login/login.svelte, web-client/iron-svelte-client/src/lib/remote-screen/remote-screen.svelte
Though I tested it a bit myself, but I'm not 100% confident in this change, would appericate someone can checkout to this branch and test it a liitle.
=> fix(web): fix firefox selection issue

Cargo.lock, Cargo.toml, ffi/Cargo.toml
This patched version of Diplomat is backporting an important fix from the more up to date versions of Diplomat.
Without this patch, the code generated by the diplomat::bridge macro contains an easy to trigger UB.
This UB is triggered by the generated C# code when passing an empty byte[] array.
=> fix(ffi): use patched diplomat

crates/ironrdp-cliprdr-native/src/stub.rs, crates/ironrdp-cliprdr-native/src/windows/cliprdr_backend.rs, crates/ironrdp-cliprdr/src/backend.rs, crates/ironrdp-cliprdr/src/lib.rs, crates/ironrdp-web/src/clipboard/mod.rs
Give a hint to the backend when the channel is actually connected & ready to process messages.
=> feat(cliprdr)!: add on_ready() callback

Cargo.lock, crates/ironrdp-bench/benches/bench.rs, crates/ironrdp-server/Cargo.toml, crates/ironrdp-server/src/display.rs, crates/ironrdp-server/src/encoder/bitmap.rs, crates/ironrdp-server/src/encoder/mod.rs, crates/ironrdp-server/src/server.rs, crates/ironrdp/examples/server.rs
subset of commits taken from #670
=> Preliminary refactoring patches for QOI

crates/ironrdp-rdpsnd/src/client.rs, crates/ironrdp-rdpsnd/src/pdu/mod.rs
Windows seems to be confused if the client replies with more formats, or unknown formats (opus).
=> fix(rdpsnd): send client formats that match server

crates/ironrdp-server/Cargo.toml, crates/ironrdp-server/src/encoder/bitmap.rs, crates/ironrdp-server/src/encoder/fast_path.rs, crates/ironrdp-server/src/encoder/mod.rs, crates/ironrdp-server/src/encoder/rfx.rs, crates/ironrdp-server/src/server.rs, crates/ironrdp-testsuite-core/tests/main.rs, crates/ironrdp-testsuite-core/tests/server/fast_path.rs, crates/ironrdp-testsuite-core/tests/server/mod.rs
A single display update can now result in multiple commands / update
code (FastPathUpdate).
The update dispatching and bitmap encoding is now done by the
UpdateEncoder itself.
(preliminary patches from #670)
=> refactor(server): make UpdateEncoder::update() an iterator 

web-client/iron-remote-desktop-rdp/src/interfaces/Extension.ts, web-client/iron-remote-desktop-rdp/src/main.ts, web-client/iron-remote-desktop/src/interfaces/Extension.ts, web-client/iron-remote-desktop/src/interfaces/ExtensionValue.ts, web-client/iron-remote-desktop/src/interfaces/RemoteDesktopModule.ts, web-client/iron-remote-desktop/src/interfaces/UserInteraction.ts, web-client/iron-remote-desktop/src/services/Config.ts, web-client/iron-remote-desktop/src/services/ConfigBuilder.ts, web-client/iron-remote-desktop/src/services/PublicAPI.ts, web-client/iron-remote-desktop/src/services/remote-desktop.service.ts, web-client/iron-svelte-client/src/lib/login/login.svelte, web-client/iron-svelte-client/src/lib/popup-screen/popup-screen.svelte
Refactored `connect` method
https://github.com/Devolutions/IronRDP/blob/fe676eeac5bb2383bc6cd571621eb718881693e9/web-client/iron-remote-desktop/src/services/PublicAPI.ts#L16-L27
as discussed here - https://github.com/Devolutions/IronRDP/pull/722#discussion_r2011775982. 
Follow-up to https://github.com/Devolutions/IronRDP/pull/722.
=> refactor(web-client): introduce `ConfigBuilder` for a better connection API

crates/ironrdp-client/src/rdp.rs, crates/ironrdp-connector/src/connection.rs, crates/ironrdp-testsuite-extra/tests/tests.rs, crates/ironrdp-web/src/session.rs, crates/ironrdp/examples/screenshot.rs, ffi/dotnet/Devolutions.IronRdp/Generated/ClientConnector.cs, ffi/dotnet/Devolutions.IronRdp/Generated/RawClientConnector.cs, ffi/dotnet/Devolutions.IronRdp/src/Connection.cs, ffi/src/connector/mod.rs
This is a cosmetic rename to better reflect the purpose of the client address field used in the initial connection sequence. No functional changes.
Closes #735
=> refactor(client): fix name of client address field

crates/ironrdp-server/src/encoder/mod.rs, crates/ironrdp-server/src/encoder/rfx.rs
The CodecChannel should only be changed when the desktop size changes.
(from #670)
=> fix(server): use desktop size for RFX channel size

web-client/iron-remote-desktop/src/iron-remote-desktop.svelte
Dynamic resizes were setting height to width and width to height, which ended up distorting things rather badly. Here's the fix.
=> fix(client): swap transposed width/height parameters for dynamic resizes

crates/iron-remote-desktop/src/lib.rs, crates/ironrdp-web/src/lib.rs, web-client/iron-remote-desktop-rdp/src/main.ts, web-client/iron-remote-desktop/src/interfaces/RemoteDesktopModule.ts, web-client/iron-remote-desktop/src/iron-remote-desktop.svelte, web-client/iron-remote-desktop/src/services/remote-desktop.service.ts
- `iron_init` is renamed to `setup`, so that
- `init` is the function for initializing the WASM module.
- `setup` is the function taking parameters for logger and performing other setting up operations.
- Since `setup` may be called after `init` is called, it’s possible to use some functions of the WASM module before calling `setup` if necessity arises.
- Common initializion code is moved to an hidden "internal" module of iron-remote-desktop crate, that is thus not part of the public API.
- Restored the "IronRDP is ready" debug log when `setup` is called.
=> refactor(web): iron_init/setup logic

crates/ironrdp-server/src/encoder/mod.rs, crates/ironrdp-server/src/lib.rs, crates/ironrdp-server/src/macros.rs
This is intended to be an internal macro.
=> fix(server)!: remove time_warn! from the public API

Cargo.lock, crates/ironrdp-graphics/Cargo.toml, crates/ironrdp-graphics/src/diff.rs, crates/ironrdp-graphics/src/lib.rs, crates/ironrdp-server/src/display.rs, crates/ironrdp-server/src/encoder/mod.rs
Keep a framebuffer and tile-diff against it, to save from
encoding/sending the same bitmap data regions.
(from #670)
=> feat(server): find & send the damaged tiles

web-client/iron-remote-desktop/src/interfaces/UserInteraction.ts, web-client/iron-remote-desktop/src/services/PublicAPI.ts, web-client/iron-svelte-client/src/lib/login/login.svelte, web-client/iron-svelte-client/src/lib/popup-screen/popup-screen.svelte, web-client/iron-svelte-client/src/lib/remote-screen/remote-screen.svelte
I've refactored the `onSessionEvent` method to use` PartialObserver` instead of a single callback.
This change gives the ability to pass `next` and `error` callbacks instead of only `next` in places like [this](https://github.com/Devolutions/devolutions-gateway/blob/e90f06f7bab3267eedb0586eb167e43d409f7f82/webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts#L336-L350) in Devolutions Gateway Standalone
=> refactor(iron-remote-desktop): use `PartialObserver` instead of single callback for `onSessionEvent`

crates/ironrdp-client/src/config.rs, crates/ironrdp-connector/src/connection_activation.rs, crates/ironrdp-pdu/src/rdp/capability_sets/bitmap_codecs.rs, crates/ironrdp-testsuite-core/tests/session/mod.rs, crates/ironrdp-web/src/session.rs
Add "--codecs remotefx:on,..." option to the client.
Depends on #782
=> feat(client): add --codecs

crates/ironrdp-client/src/app.rs, crates/ironrdp-client/src/config.rs, crates/ironrdp-client/src/rdp.rs, crates/ironrdp-graphics/src/pointer.rs
Render cursor icon at client side with `winit` custom cursor API. This should close #255.
Tested on Wayland.
Closes #251 
Closes #252 
Closes #253 
Closes #254 
Closes #255
=> feat(client): support for hardware cursor

Cargo.lock, crates/ironrdp-server/Cargo.toml
Patch bump including the ironrdp-tokio dependency.
Closes #814
=> chore(release): prepare ironrdp-server 0.6.1

web-client/iron-remote-desktop/src/iron-remote-desktop.svelte
QA hasn't created an issue about it yet, but it was causing "Uncaught TypeError displayed in dev console after enabling Full Screen mode".
=> fix(web): remove window resize listener on component destroy

web-client/iron-remote-desktop/src/iron-remote-desktop.svelte
I put it in a wrong place in https://github.com/Devolutions/IronRDP/pull/823
=> fix(web): move `onDestroy` function out of the `scaleSession` function

web-client/iron-remote-desktop/src/services/remote-desktop.service.ts
When the session ends with an error, `iron-remote-desktop` raises `ERROR` in pair with `TERMINATED`. The handling function in Devolutions Gateway Standalone handles these types of events similarly. As a result, we see only the message from the `TERMINATED` event in the `error notify bar`, because the message from the `ERROR` is overwritten.
This PR fixes the issue by only raising the `TERMINATED` with the error backtrace.
=> fix(web): raise only `TERMINATED` message on session termination with the error backtrace

ffi/dotnet/Devolutions.IronRdp.AvaloniaExample/MainWindow.axaml.cs
When running on non-Windows, HandleClipboardEvents will create an infinite loop consuming 100% CPU.
This PR calls HandleClipboardEvents only when on Windows.
=> fix: avoids infinite loop in HandleClipboardEvents when not on Windows

crates/ironrdp-tokio/src/reqwest.rs
Hi,
I add a public `ReqwestNetworkClient::send` method. It is needed for the Devolutions-Gateway. More context: https://github.com/Devolutions/IronRDP/pull/839#pullrequestreview-2974986096
=> feat(ironrdp-tokio): add async `ReqwestNetworkClient::send` method

crates/ironrdp-web/src/session.rs, web-client/iron-remote-desktop-rdp/src/main.ts
This change adds a new extension allowing users to turn off Network Level Authentication (CredSSP) for Azure AD/Entra scenarios.
Hi from Cloudflare!
=> feat(web): add enableCredssp extension to support auth to AzureAd/Entra

STYLE.md
For error messages: use proper abbreviation casing, e.g., IPv4 and IPv6 (not ipv4/ipv6).
For inline comments, no period for brief comments (e.g., `// VER`, `// RSV`, `// ATYP`)
=> docs: clarify STYLE.md

Cargo.toml, crates/ironrdp-connector/src/connection_activation.rs, crates/ironrdp-dvc/src/lib.rs, crates/ironrdp-error/src/lib.rs, crates/ironrdp-fuzzing/src/oracles/mod.rs, crates/ironrdp-graphics/src/rlgr.rs, crates/ironrdp-mstsgu/src/lib.rs, crates/ironrdp-pdu/src/basic_output/surface_commands/tests.rs, crates/ironrdp-pdu/src/mcs.rs, crates/ironrdp-pdu/src/rdp/capability_sets/bitmap_codecs/tests.rs, crates/ironrdp-pdu/src/rdp/server_license/client_new_license_request/tests.rs, crates/ironrdp-pdu/src/rdp/server_license/client_platform_challenge_response/test.rs, crates/ironrdp-pdu/src/rdp/server_license/licensing_error_message/test.rs, crates/ironrdp-pdu/src/rdp/server_license/server_license_request/tests.rs, crates/ironrdp-pdu/src/rdp/session_info/tests.rs, crates/ironrdp-pdu/src/utils.rs, crates/ironrdp-rdpdr/src/pdu/efs.rs, crates/ironrdp-rdpdr/src/pdu/esc.rs, crates/ironrdp-rdpdr/src/pdu/esc/ndr.rs, crates/ironrdp-rdpdr/src/pdu/esc/rpce.rs, crates/ironrdp-rdpdr/src/pdu/mod.rs, crates/ironrdp-rdpsnd-native/src/cpal.rs, crates/ironrdp-server/src/server.rs, crates/ironrdp-svc/src/lib.rs
The name of the lint is self-explanatory 😁
=> refactor: add redundant_imports rustc style/readability lint

crates/ironrdp-client/src/config.rs, crates/ironrdp-connector/src/connection.rs, crates/ironrdp-connector/src/lib.rs, crates/ironrdp-testsuite-extra/tests/tests.rs, crates/ironrdp-web/src/session.rs, crates/ironrdp/examples/screenshot.rs, ffi/src/connector/config.rs
This PR allows you to pass a timezone to the remote desktop.
At some point, the Microsoft spec for the timezone bias types should be unsigned based on implementations of this spec in other clients. Now the docs have been updated to have the timezone bias type as a signed integer, so I've updated the `TimezoneInfo` struct to reflect that.
=> feat: allow users to specify a timezone

Cargo.toml
This lint checks the float literals that cannot be represented as the underlying type without loss.
=> chore: add lossy_float_literal clippy correctness lint

web-client/iron-remote-desktop/src/services/remote-desktop.service.ts
This resolves an issue with Unicode input that happens under _Chrome_, where entering `Alt` codes results in broken modifier state and broken input in general.
This happens because of how _Chrome_ handles `KeyboardEvent` key and code in this particular case. For example, holding `Alt`, pressing 1, 2, 3 on a numpad, then releasing `Alt` will result in events with the following key/code values being passed to `sendKeyboard`:
`{ "key": "Alt", "code": "AltLeft" ,"type": "keydown" }`
`{ "key": "1", "code": "Numpad1" ,"type": "keydown" }`
`{ "key": "1", "code": "Numpad1" ,"type": "keyup" }`
`{ "key": "2", "code": "Numpad2" ,"type": "keydown" }`
`{ "key": "2", "code": "Numpad2" ,"type": "keyup" }`
`{ "key": "3", "code": "Numpad3" ,"type": "keydown" }`
`{ "key": "3", "code": "Numpad3" ,"type": …
=> fix(web): make check for `isUnicodeCharacter` in `sendKeyboard` more strict

Cargo.toml, crates/ironrdp-cliprdr-native/src/windows/utils.rs
This lint warns on usage of `std::mem::forget`. If it's needed, we should silence the lint and justify that it's used mindfully.
=> chore: add `mem_forget` clippy correctness lint

Cargo.toml
`mixed_read_write_in_expression`  checks for a read and a write to the same variable, where whether the read occurs before or after the write depends on the evaluation order of sub-expressions.
=> chore: add `mixed_read_write_in_expression` clippy correctness lint

crates/ironrdp-cliprdr-native/src/windows.rs
When the system clipboard updates, we receive an `Updated` event. Then we try to open it, but we can get `AccessDenied` error because the clipboard may still be locked for another window (like _Notepad_). To handle this, we have special logic that attempts to open the clipboard in the event of such errors. 
The problem is that nothing in the code actually sets the `ClipboardAccessDenied` error to be able to run the retrieval logic. This PR fixes it.
=> fix(clipbrdr-native): map `E_ACCESSDENIED` WinAPI error code to `ClipboarAccessDenied` error

Cargo.toml, crates/ironrdp-client/src/main.rs, crates/ironrdp-client/src/rdp.rs, crates/ironrdp-connector/src/connection.rs, crates/ironrdp-connector/src/lib.rs, crates/ironrdp-pdu/src/rdp/server_error_info.rs, xtask/src/clean.rs, xtask/src/cov.rs
This lint checks for non-ASCII characters in string and char literals.
=> refactor: add `non_ascii_literal` clippy correctness lint

Cargo.toml
This lint checks bit shifting operations combined with bit masking/combining operators and suggest using parentheses.
=> chore: add `precedence_bits` clippy correctness lint

crates/iron-remote-desktop/src/lib.rs, crates/iron-remote-desktop/src/session.rs, crates/ironrdp-cliprdr/src/backend.rs, crates/ironrdp-cliprdr/src/lib.rs, crates/ironrdp-web/src/clipboard.rs, crates/ironrdp-web/src/session.rs, web-client/iron-remote-desktop/src/enums/SessionEventType.ts, web-client/iron-remote-desktop/src/interfaces/UserInteraction.ts, web-client/iron-remote-desktop/src/iron-remote-desktop.svelte, web-client/iron-remote-desktop/src/lib/stores/componentLifecycleStore.ts, web-client/iron-remote-desktop/src/lib/stores/runWhenFocusedStore.ts, web-client/iron-remote-desktop/src/services/PublicAPI.ts, web-client/iron-remote-desktop/src/services/clipboard.service.ts, web-client/iron-remote-desktop/src/services/remote-desktop.service.ts
This PR adds:
* auto clipboard mode. 
When it's enabled, the clipboard will be automatically monitored for changes, and updates from the server will be automatically saved to the local clipboard (this is the old logic; nothing has changed). 
* manual clipboard mode. 
One calls dedicated functions to interact with the clipboard.
=> fix(web)!: replace current clipboard logic with auto and manual clipboard modes

web-client/iron-remote-desktop/src/enums/ClipboardApiSupported.ts, web-client/iron-remote-desktop/src/enums/SessionEventType.ts, web-client/iron-remote-desktop/src/services/clipboard.service.ts
Firefox versions before v127 do not support the write() method - only writeText(). Therefore, the Extended Clipboard checkbox must be automatically disabled.
=> fix(web): implement text-only clipboard for outdated versions of Firefox browser

crates/ironrdp-dvc-pipe-proxy/src/platform/windows.rs
We don't need Message mode anymore, message defragmentation logic is implemented in https://github.com/Devolutions/now-proto/pull/41
=> fix(dvc-pipe-proxy): change dvc proxy pipe mode from Message to Byte on Windows

Cargo.toml
[`rest_pat_in_fully_bound_structs`](https://rust-lang.github.io/rust-clippy/stable/index.html#/rest_pat_in_fully_bound_structs):
> Checks for unnecessary ‘..’ pattern binding on struct when all fields are explicitly matched.
=> chore: enable `rest_pat_in_fully_bound_structs` clippy lint
