ironrdp/src/gcc/security_data.rs
ironrdp/src/rdp/capability_sets.rs

- Fixed issue #8 ;
- Ran cargo fmt for the capability sets.

Remove unwrap for Security GCC block

---

ironrdp/src/gcc/security_data.rs
ironrdp/src/gcc/security_data/test.rs
ironrdp/src/rdp/finalization_messages.rs
ironrdp/src/rdp/server_license.rs
ironrdp/src/rdp/server_license/server_license_request.rs
ironrdp/src/rdp/server_license/server_license_request/cert.rs
ironrdp/src/rdp/session_info/logon_info.rs

Added allocations bounds according to the fuzzers results (fixed issue #14 )

Fix fuzzers

---

ironrdp/fuzz/fuzz_targets/fuzz_pdu.rs
ironrdp/src/rdp.rs
ironrdp/src/rdp/headers.rs
ironrdp/src/rdp/server_error_info.rs
ironrdp_client/src/active_session/x224.rs
ironrdp_client/src/connection_sequence.rs
ironrdp_client/src/connection_sequence/user_info.rs
ironrdp_client/src/errors.rs

1. Implemented parsing of the Server Set Error PDU with detailed description;
2. Integrated the PDU to IronRDP client, set the corresponding capability flag.

Server Set Error Info PDU

---

ironrdp/src/rdp/client_info.rs

As specified in [RDP protocol doc](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/526ed635-d7a9-4d3c-bbe1-4e3fb17585f4)
we should be able to ignore invalid date encoding.

Fix decoding for invalid SystemDate

---

.github/workflows/ci.yml
rust-toolchain.toml

ci: fix clippy job

---

.github/workflows/ci.yml
ffi/wasm/src/input.rs
ironrdp-input/src/lib.rs
ironrdp-input/tests/fastpath_packets.rs
ironrdp-input/tests/smoke.rs

feat(input): support for extended keys

---

ffi/wasm/Cargo.toml
ffi/wasm/src/session.rs
ironrdp-input/src/lib.rs
ironrdp-input/tests/fastpath_packets.rs

It is intented to be used when focus is lost.
Issue: ARC-132

feat(input): release all keys and buttons API

---

ffi/wasm/src/session.rs
ironrdp-core/src/input/fast_path.rs
ironrdp-gui-client/src/gui/input.rs
ironrdp-input/src/lib.rs
ironrdp-input/tests/fastpath_packets.rs
ironrdp-input/tests/smoke.rs

feat(input): synchronize event support

---

ffi/wasm/src/input.rs
ironrdp-core/src/input/mouse.rs
ironrdp-core/src/input/tests.rs
ironrdp-gui-client/src/gui/input.rs
ironrdp-input/src/lib.rs
ironrdp-input/tests/fastpath_packets.rs

feat(input): horizontal and vertical mouse wheel rotations

---

ffi/wasm/src/session.rs
ironrdp-core/src/input/mouse.rs
ironrdp-core/src/input/mouse_x.rs
ironrdp-core/src/input/tests.rs
ironrdp-gui-client/src/gui/input.rs
ironrdp-input/src/lib.rs
ironrdp-input/tests/fastpath_packets.rs

fix(input): MousePdu wheel rotation units encoding

---

.github/workflows/ci.yml
.github/workflows/fuzz.yml
.gitignore
README.md
xtask/src/cli.rs
xtask/src/main.rs
xtask/src/tasks.rs

- Fix initial fuzz workflow
- Extend CLI options for xtask fuzz action
- Update list of supported codecs in README.md
- Improve Fuzz workflow to run targets longer and in parallel

Improve Fuzz worflow

---

Cargo.lock
crates/ironrdp-client/src/gui.rs
crates/ironrdp-client/src/main.rs
crates/ironrdp-connector/src/connection.rs
crates/ironrdp-connector/src/lib.rs
crates/ironrdp-connector/src/license_exchange.rs
crates/ironrdp-pdu/Cargo.toml
crates/ironrdp-pdu/src/crypto/rsa.rs
crates/ironrdp-pdu/src/lib.rs
crates/ironrdp-pdu/src/rdp/server_license.rs
crates/ironrdp-pdu/src/rdp/server_license/server_license_request.rs
crates/ironrdp-pdu/src/rdp/server_license/tests.rs
crates/ironrdp-pdu/src/rdp/vc/dvc/gfx/graphics_messages.rs
crates/ironrdp-pdu/src/rdp/vc/dvc/gfx/graphics_messages/server.rs
crates/ironrdp-session/src/lib.rs

Also commented out some properties advertising not yet supported features in GCC blocks.

fix: proprietary certificate public key extraction

---

crates/ironrdp-web/src/error.rs
crates/ironrdp-web/src/session.rs
web-client/iron-svelte-client/README.md

WebSocket state is checked after `WebSocket::open` is called.

feat(web): clarify error on proxy connection

---

ARCHITECTURE.md
README.md
crates/ironrdp-acceptor/Cargo.toml
crates/ironrdp-acceptor/README.md
crates/ironrdp-blocking/README.md
crates/ironrdp-client/Cargo.toml
crates/ironrdp-client/README.md
crates/ironrdp-cliprdr/Cargo.toml
crates/ironrdp-cliprdr/README.md
crates/ironrdp-pdu/README.md
crates/ironrdp-pdu/src/cursor.rs
crates/ironrdp-pdu/src/write_buf.rs
crates/ironrdp-rdpdr/Cargo.toml
crates/ironrdp-rdpdr/README.md
crates/ironrdp-server/Cargo.toml
crates/ironrdp-server/README.md
crates/ironrdp-svc/src/lib.rs
crates/ironrdp/Cargo.toml
crates/ironrdp/examples/screenshot.rs

cc @pacmancoder @ibeckermayer 
I took some time to elaborate the high-level documentation of the repository a bit more.

doc: elaborate high-level documentation

---

crates/ironrdp-rdpdr/src/backend/mod.rs
crates/ironrdp-rdpdr/src/backend/noop.rs
crates/ironrdp-rdpdr/src/lib.rs
crates/ironrdp-rdpdr/src/pdu/efs.rs
crates/ironrdp-rdpdr/src/pdu/esc.rs

Adds `EstablishContextCall` and `EstablishContextReturn` in the process.

Consolidates the RdpdrBackend smartcard calls into a single function.

---

crates/ironrdp-pdu/src/utils.rs
crates/ironrdp-rdpdr/src/pdu/esc.rs

Corresponds to https://github.com/gravitational/teleport/pull/33004

`ListReadersCall`, `ListReadersReturn`

---

crates/ironrdp-rdpdr/src/pdu/esc.rs

Adds handling for multiple ioctl codes which don't require new PDUs.

Adds `EndTransaction`, `Disconnect`, `Cancel`, and `IsValidContext`

---

Cargo.toml
crates/ironrdp-async/src/connector.rs
crates/ironrdp-async/src/framed.rs
crates/ironrdp-blocking/src/connector.rs
crates/ironrdp-blocking/src/framed.rs
crates/ironrdp-cliprdr/src/backend.rs
crates/ironrdp-cliprdr/src/pdu/format_data/file_list.rs
crates/ironrdp-cliprdr/src/pdu/format_data/mod.rs
crates/ironrdp-graphics/src/rdp6/bitmap_stream/encoder.rs
crates/ironrdp-pdu/src/cursor.rs
crates/ironrdp-pdu/src/rdp/vc/dvc.rs
crates/ironrdp-rdpdr/src/backend/mod.rs
crates/ironrdp-rdpdr/src/backend/noop.rs
crates/ironrdp-rdpdr/src/lib.rs
crates/ironrdp-rdpdr/src/pdu/efs.rs
crates/ironrdp-rdpdr/src/pdu/esc.rs
crates/ironrdp-rdpdr/src/pdu/esc/ndr.rs
crates/ironrdp-rdpdr/src/pdu/esc/rpce.rs
crates/ironrdp-web/src/network_client.rs

Small teaks and improvements I had in my git working tree.
Each teak has its own commit.

Maintenance and follow-up

---

crates/ironrdp-pdu/src/cursor.rs
crates/ironrdp-rdpdr/src/backend/mod.rs
crates/ironrdp-rdpdr/src/backend/noop.rs
crates/ironrdp-rdpdr/src/lib.rs
crates/ironrdp-rdpdr/src/pdu/efs.rs
crates/ironrdp-rdpdr/src/pdu/mod.rs

Also changes `FilesystemRequest` to be named `ServerDriveIoRequest`.

Adds `ServerDriveQueryInformationRequest`

---

.github/workflows/npm-publish.yml
Cargo.lock
Cargo.toml

- Fix npm-publish workflow
- Publish to npmjs
- Remove softbuffer dependency patch

ci: adjust npm-publish workflow

---

crates/ironrdp-web/src/session.rs
web-client/iron-remote-gui/package.json
web-client/iron-remote-gui/public/package.json

Issue: https://github.com/Devolutions/IronRDP/issues/249

revert(web): disable RDP6 bitmap codec temporarily

---

crates/ironrdp-session/src/image.rs

fix(session): add out of bounds cursor rendering check

---

web-client/.prettierrc.yaml
web-client/iron-remote-gui/.eslintrc.yaml
web-client/iron-svelte-client/.eslintrc.yaml

Updated Prettier configurations to avoid ending character conflict.
Reference:
https://prettier.io/docs/en/options 
end of line options
https://stackoverflow.com/questions/53516594/why-do-i-keep-getting-eslint-delete-cr-prettier-prettier

Update prettier end of line configuration

---

crates/ironrdp-connector/src/license_exchange.rs

Follow up to #278
@thenextman pointed me to this document: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpele/8f9b860a-3687-401d-b3bc-7e9f5d4f7528
Actually, the STATUS_VALID_CLIENT error code IS expected at any point during the licensing process.
It’s likely that #278 was indeed the correct fix for #268. Phew!
The weird control flow pattern will be addressed by #269

fix(connector): STATUS_VALID_CLIENT IS expected

---

crates/ironrdp-async/src/connector.rs
crates/ironrdp-blocking/src/connector.rs
crates/ironrdp-client/src/network_client.rs
crates/ironrdp-client/src/rdp.rs
crates/ironrdp-connector/src/connection.rs
crates/ironrdp-connector/src/credssp.rs
crates/ironrdp-connector/src/lib.rs
crates/ironrdp-web/Cargo.toml
crates/ironrdp-web/src/network_client.rs
crates/ironrdp-web/src/session.rs
crates/ironrdp/examples/screenshot.rs
web-client/iron-remote-gui/README.md

Applies follow-up suggestions for #260

refactor(credssp): follow up to #260

---

crates/ironrdp-graphics/src/rectangle_processing.rs
crates/ironrdp-pdu/src/geometry.rs

- Fixed bug and unit tests
- Validated that RFX and other codecs are still working as expected
Closes #249

fix(rfx): Fix invalid rectangle intersection intersection logic (RFX visual artifacts fix)

---

crates/ironrdp-pdu/src/rdp/refresh_rectangle.rs
crates/ironrdp-pdu/src/rdp/suppress_output.rs
crates/ironrdp-server/src/capabilities.rs
crates/ironrdp-server/src/server.rs
crates/ironrdp/examples/server.rs

cc @elmarco 
Non-controversial changes addressing remaining comments from PR #198.

refactor: follow-up for PR #198

---

crates/ironrdp-server/src/capabilities.rs

This helps FreeRDP, despite not being required by mstcs: https://github.com/FreeRDP/FreeRDP/issues/9612

fix(server): advertize FASTPATH_OUTPUT

---

web-client/iron-remote-gui/package-lock.json
web-client/iron-remote-gui/package.json
web-client/iron-remote-gui/public/package.json

chore(release): prepare iron-remote-gui for 0.11.2

---

Cargo.lock
crates/ironrdp-acceptor/src/connection.rs
crates/ironrdp-client/src/config.rs
crates/ironrdp-client/src/main.rs
crates/ironrdp-client/src/rdp.rs
crates/ironrdp-cliprdr-native/Cargo.toml
crates/ironrdp-cliprdr-native/src/lib.rs
crates/ironrdp-cliprdr-native/src/stub.rs
crates/ironrdp-cliprdr/src/lib.rs
crates/ironrdp-connector/src/connection.rs
crates/ironrdp-dvc/src/lib.rs
crates/ironrdp-pdu/README.md
crates/ironrdp-pdu/src/gcc/core_data/client.rs
crates/ironrdp-pdu/src/input/fast_path.rs
crates/ironrdp-pdu/src/input/mod.rs
crates/ironrdp-pdu/src/input/mouse_rel.rs
crates/ironrdp-pdu/src/rdp/capability_sets/input.rs
crates/ironrdp-rdpdr/src/lib.rs
crates/ironrdp-rdpsnd/src/lib.rs
crates/ironrdp-server/Cargo.toml
crates/ironrdp-server/src/builder.rs
crates/ironrdp-server/src/capabilities.rs
crates/ironrdp-server/src/handler.rs
crates/ironrdp-server/src/server.rs
crates/ironrdp-session/src/active_stage.rs
crates/ironrdp-session/src/x224/mod.rs
crates/ironrdp-svc/src/lib.rs
crates/ironrdp-web/src/session.rs
crates/ironrdp/Cargo.toml
crates/ironrdp/examples/server.rs

Add basic building blocks for static channel handling and testing with a dummy clipboard implementation.

server: add static channel and basic clipboard 

---

crates/ironrdp-client/src/gui.rs
crates/ironrdp-input/src/lib.rs
crates/ironrdp-web/src/input.rs
crates/ironrdp-web/src/session.rs
web-client/iron-remote-gui/src/interfaces/UserInteraction.ts
web-client/iron-remote-gui/src/services/PublicAPI.ts
web-client/iron-remote-gui/src/services/wasm-bridge.service.ts
web-client/iron-svelte-client/src/lib/remote-screen/remote-screen.svelte

feat(input): Added unicode input to `ironrdp-web` and `ironrdp-input`

---

web-client/iron-remote-gui/package-lock.json
web-client/iron-remote-gui/package.json
web-client/iron-remote-gui/public/package.json

chore(release): prepare for iron-remote-gui v0.11.4

chore(release): prepare for iron-remote-gui v0.11.5

---

crates/ironrdp-session/src/x224/mod.rs

even in cases where the server doesn't send a Capabilities Request as expected. This mimics the logic in FreeRDP, and empirically appears to fix a bug where DVC channels behave irregularly.

Adds logic for sending Capabilities Response as first DVC message

---

.github/workflows/fuzz.yml
fuzz/Cargo.toml
xtask/src/main.rs

We forgot to add it back when it was originally written.

ci: enable the cliprdr_format fuzz harness

---

crates/ironrdp-server/src/display.rs
crates/ironrdp-server/src/encoder/mod.rs
crates/ironrdp-server/src/server.rs

This allows server implementation to set the pointer shape.

server: add pointer DisplayUpdate

---

crates/ironrdp-pdu/src/rdp/server_license/server_upgrade_license.rs

fix(fuzz): add missing `ensure_size!` in `ServerUpgradeLicense`

---

ffi/dotnet/Devolutions.IronRdp/Generated/ConfigBuilder.cs
ffi/dotnet/Devolutions.IronRdp/Generated/RawConfigBuilder.cs

quick short fix, add missing generated files.

fix(ffi): include forgotten generated files

---

ffi/dotnet/Devolutions.IronRdp.AvaloniaExample/MainWindow.axaml
ffi/dotnet/Devolutions.IronRdp.AvaloniaExample/MainWindow.axaml.cs
ffi/dotnet/Devolutions.IronRdp.AvaloniaExample/Program.cs
ffi/dotnet/Devolutions.IronRdp/Generated/ActiveStage.cs
ffi/dotnet/Devolutions.IronRdp/Generated/RawActiveStage.cs
ffi/src/session/mod.rs

Allow ffi active stage to gracefully shut down.
1. Added FFI function
2. Updated example

feat(ffi): add graceful shutdown API

---

web-client/iron-remote-gui/src/services/wasm-bridge.service.ts

The value should be typed IronRdpError instead. We perhaps need to publish a small new patch for this.
DPS-10099

fix(web): fix wrong type assertion caused error

---

crates/ironrdp-rdpsnd-native/examples/cpal.rs
crates/ironrdp-rdpsnd-native/src/cpal.rs
crates/ironrdp-rdpsnd-native/src/lib.rs
crates/ironrdp-rdpsnd/src/client.rs
crates/ironrdp-rdpsnd/src/pdu/mod.rs
crates/ironrdp-rdpsnd/src/server.rs
crates/ironrdp-server/src/builder.rs
crates/ironrdp-server/src/display.rs
crates/ironrdp-server/src/encoder/mod.rs
crates/ironrdp-server/src/encoder/rfx.rs
crates/ironrdp-server/src/server.rs
crates/ironrdp-server/src/sound.rs
crates/ironrdp-testsuite-core/tests/rdpsnd/mod.rs

refactor: follow up to PR #467

---

crates/ironrdp-server/src/server.rs

Learn to exit the run() loop from user.

feat(server): add Quit event

---

crates/ironrdp-cliprdr-native/src/lib.rs
crates/ironrdp-cliprdr-native/src/windows.rs

Follow-up to comment https://github.com/Devolutions/IronVNC/pull/518#issuecomment-2252594699

fix(cliprdr): exposed HWND for Windows native cliprdr API

---

Cargo.lock
Cargo.toml
crates/ironrdp-rdpdr-native/Cargo.toml
crates/ironrdp-rdpdr-native/README.md
crates/ironrdp-rdpdr-native/src/lib.rs
crates/ironrdp-rdpdr-native/src/nix/backend.rs
crates/ironrdp-rdpdr-native/src/nix/mod.rs
crates/ironrdp-rdpdr-native/src/nix/simple.rs
crates/ironrdp-rdpdr/src/backend/mod.rs
crates/ironrdp-rdpdr/src/backend/noop.rs
crates/ironrdp-rdpdr/src/lib.rs

As mentiond in [file upload support](https://github.com/Devolutions/IronRDP/issues/110). i implemented a simple file backend,which supports file upload/download. @CBenoit @ibeckermayer

feat(rdpdr): simple file backend for file upload/download

---

crates/ironrdp-server/src/server.rs

When display updates and server events are competing, tokio::select!() will randomly pick one branch and process one event.
This is good for fairness, except when the display updates are big, and delay other messages for example wave data. We may end up in a situation where the server events queue grows and audio data gets delayed.
To avoid this situation, let's flush all server events and drop audio frames when they are queuing up.
This introduce some bias for server events, since all pending server events will be processed before other updates/inputs.
There are many different ways to tackle the problem, this simple approach seems to work fine atm.

RFC: feat(server): flush server events, avoid audio buffer filling up

---

crates/ironrdp-async/src/connector.rs
crates/ironrdp-blocking/src/connector.rs
crates/ironrdp-connector/src/credssp.rs
ffi/src/credssp/mod.rs

Refactored CredsspSequence to remove direct dependency on ClientConnector. This allows CredSSPSequence to be reused in cases where one doesn't necessarily create a clientconnector. As  an example i am building a rust POC that performs a MITM for an RDP connection and don't need to create a client connector directly.

fix!: remove dependency on ClientConnector in CredsspSequence

---

crates/ironrdp-web/Cargo.toml
crates/ironrdp-web/src/canvas.rs
crates/ironrdp-web/src/session.rs
web-client/iron-remote-gui/src/interfaces/UserInteraction.ts
web-client/iron-remote-gui/src/iron-remote-gui.svelte
web-client/iron-remote-gui/src/services/PublicAPI.ts
web-client/iron-remote-gui/src/services/wasm-bridge.service.ts
web-client/iron-svelte-client/src/app.html
web-client/iron-svelte-client/src/lib/login/login.svelte
web-client/iron-svelte-client/src/lib/popup-screen/popup-screen.svelte
web-client/iron-svelte-client/src/routes/popup-session/+page.svelte

Allow IronRdp Web to use display control for smart resizing.
Add example to use popup window for connection
Demo:
https://github.com/user-attachments/assets/d9f94937-3ac8-4788-b70e-6292cc8ecde0

feat(web): allow dynamic resize for web

---

Cargo.toml
crates/ironrdp-acceptor/src/connection.rs
crates/ironrdp-server/src/server.rs
crates/ironrdp/Cargo.toml
crates/ironrdp/examples/server.rs

Follow up to PR https://github.com/Devolutions/IronRDP/pull/558
cc @elmarco

refactor: follow up to PR 558

---

crates/ironrdp-server/src/server.rs

Add a server event to lookup the actual server listen address.

feat(server): add GetLocalAddr

---

Cargo.lock
Cargo.toml
crates/ironrdp-ainput/Cargo.toml
crates/ironrdp-connector/Cargo.toml
crates/ironrdp/Cargo.toml
crates/ironrdp/examples/screenshot.rs
crates/ironrdp/src/lib.rs

- Bump some deps
- Fix build of screenshot
- Replace "bmp" with "image" crate

Some fixes and changes for example code 

---

Cargo.lock
Cargo.toml
crates/ironrdp-acceptor/Cargo.toml
crates/ironrdp-async/Cargo.toml
crates/ironrdp-blocking/Cargo.toml
crates/ironrdp-server/Cargo.toml
crates/ironrdp-session/Cargo.toml
crates/ironrdp/Cargo.toml

Crates to release:
- ironrdp-acceptor -> 0.2.0
- ironrdp-async -> 0.2.0
- ironrdp-blocking -> 0.2.0
- ironrdp-session -> 0.2.0
- ironrdp-server -> 0.3.0
- ironrdp -> 0.7.0

chore: prepare release

---

Cargo.lock
crates/ironrdp-cliprdr-format/Cargo.toml
crates/ironrdp-futures/Cargo.toml
crates/ironrdp-rdcleanpath/Cargo.toml
crates/ironrdp-rdpdr-native/Cargo.toml
fuzz/Cargo.lock

- ironrdp-cliprdr-format
- ironrdp-futures
- ironrdp-rdcleanpath
- ironrdp-rdpdr-native

chore(release): prepare for publishing

---

crates/ironrdp-server/src/helper.rs

This is in general more convenient than DER files.

feat(server): make TlsIdentityCtx accept PEM files

---

.github/workflows/coverage.yml
.github/workflows/fuzz.yml
.github/workflows/npm-publish.yml
.github/workflows/nuget-publish.yml

Start updating Ubuntu GitHub runners away from 20.04

ci: start updating ubuntu runners

---

web-client/iron-remote-gui/src/interfaces/UserInteraction.ts
web-client/iron-remote-gui/src/iron-remote-gui.svelte
web-client/iron-remote-gui/src/services/PublicAPI.ts
web-client/iron-remote-gui/src/services/wasm-bridge.service.ts
web-client/iron-svelte-client/src/lib/login/login.css
web-client/iron-svelte-client/src/lib/login/login.svelte

- Add setEnableClipboard function in user interface 
- Updated demo with clipboard control

feat(web): implement clipboard enable/disable

---

crates/ironrdp-connector/src/connection.rs
crates/ironrdp-pdu/src/rdp/client_info.rs
crates/ironrdp-testsuite-core/src/client_info.rs

I found this value while trying to connect to ironrdp/server example with Windows App for iOS.

fix(pdu): make AddressFamily parsing resilient

---

web-client/iron-remote-gui/src/iron-remote-gui.svelte
web-client/iron-remote-gui/src/services/wasm-bridge.service.ts

https://github.com/user-attachments/assets/426b8b9d-dd6d-4ab5-903d-3f22f00e838d

fix(web):allow keyboard input even if the mouse is off the area of canvas

---

web-client/iron-svelte-client/README.md
web-client/iron-svelte-client/src/lib/login/login.svelte

https://github.com/user-attachments/assets/8a6c1238-e369-4f71-a077-5d592d853f58

feat(web-client): let iron-svelte-client use automatic token generation

---

Cargo.lock
crates/ironrdp-async/src/lib.rs
crates/ironrdp-client/Cargo.toml
crates/ironrdp-client/src/lib.rs
crates/ironrdp-client/src/rdp.rs
crates/ironrdp-tokio/Cargo.toml
crates/ironrdp-tokio/src/lib.rs
crates/ironrdp-tokio/src/reqwest.rs

Move the client ReqwestNetworkClient to ironrdp-tokio, so other clients can optionally use the implementation.

feat(tokio): add reqwest feature

---

crates/ironrdp-session/src/active_stage.rs
crates/ironrdp-session/src/fast_path.rs
crates/ironrdp-session/src/image.rs
crates/ironrdp-session/src/pointer.rs
ffi/src/graphics.rs
ffi/src/session/mod.rs

As I am working on switching RDW-RDP (https://gitlab.gnome.org/malureau/rdw) from FreeRDP to IronRDP, I'd need those changes.

Session-related improvements

---

Cargo.lock
crates/ironrdp-client/Cargo.toml
crates/ironrdp-cliprdr-native/Cargo.toml
crates/ironrdp-cliprdr-native/src/windows.rs
crates/ironrdp-cliprdr-native/src/windows/clipboard_impl.rs
crates/ironrdp-cliprdr-native/src/windows/cliprdr_backend.rs
crates/ironrdp-cliprdr-native/src/windows/os_clipboard.rs
crates/ironrdp-cliprdr-native/src/windows/utils.rs

build(deps): update `windows` crate to 0.61.1

---

Cargo.lock
crates/ironrdp-client/Cargo.toml
crates/ironrdp-client/src/config.rs
crates/ironrdp-client/src/lib.rs
crates/ironrdp-client/src/rdp.rs
crates/ironrdp-client/src/ws.rs
crates/ironrdp-web/src/session.rs

feat(client): add support for RDCleanPath

---

Cargo.lock
crates/iron-remote-desktop/Cargo.toml
crates/iron-remote-desktop/src/clipboard.rs
crates/iron-remote-desktop/src/cursor.rs
crates/iron-remote-desktop/src/error.rs
crates/iron-remote-desktop/src/input.rs
crates/iron-remote-desktop/src/lib.rs
crates/iron-remote-desktop/src/session.rs
crates/ironrdp-web/Cargo.toml
crates/ironrdp-web/src/clipboard/mod.rs
crates/ironrdp-web/src/clipboard/transaction.rs
crates/ironrdp-web/src/error.rs
crates/ironrdp-web/src/input.rs
crates/ironrdp-web/src/lib.rs
crates/ironrdp-web/src/session.rs
web-client/iron-remote-desktop-rdp/package.json
web-client/iron-remote-desktop-rdp/public/package.json

feat(ironrdp-web): implement `iron-remote-desktop` crate to share code between ironrdp-web and ironvnc-web

---

crates/iron-remote-desktop/src/clipboard.rs
crates/iron-remote-desktop/src/error.rs
crates/iron-remote-desktop/src/input.rs
crates/iron-remote-desktop/src/lib.rs
crates/iron-remote-desktop/src/session.rs

There was still some room for improvement.

fix(web): improve make_bridge! macro hygiene

---

ARCHITECTURE.md

This small PR fixes the `fuzz/README.md` location in `ARCHITECTURE.md`.

docs: update fuzz location in ARCHITECTURE.md

---

web-client/iron-remote-desktop-rdp/public/package.json
web-client/iron-remote-desktop/public/package.json

- iron-remote-desktop v0.5.4
- iron-remote-desktop-rdp v0.2.3

chore(release): prepare web packages for publishing

---

web-client/iron-remote-desktop/src/iron-remote-desktop.svelte

When the server sends the clipboard update, we write it to our clipboard. But this new clipboard data was then processed as a new one, so we sent it back to the server. This commit fixes this behavior by tracking the data that we received from the server.

fix(web): fix issue when clipboard monitoring treats clipboard update  from server as the local update

---

crates/ironrdp-web/src/lib.rs

style(web): extern crate getrandom2 as _

---

crates/ironrdp-client/src/app.rs

refactor: follow up to PR #906

---

crates/ironrdp-server/src/encoder/mod.rs

Instead use a `Option` as a slot from which the value can be moved out temporarily when necessary.

refactor(server): remove needless sync primitives

---

crates/ironrdp-rdpdr/src/lib.rs
crates/ironrdp-rdpdr/src/pdu/efs.rs
crates/ironrdp-rdpdr/src/pdu/mod.rs

This PR adds support for removing redirected devices.

feat(rdpdr): support device removal
